### ISSUE TITLE
能不能提供单元测试simple

### ISSUE THREAD

**Issue by charleszhn** [2881099/csredis#10]
使用分布式缓存时提示与最新版本有冲突，netcore 2.1.0 rc1

**Comment by 2881099** [comment]
原作者有提供 test https://github.com/ctstone/csredis 
我移值的时候去掉了单元测试部分。

更新您的 .net core 版本可以解决冲突问题。

**Comment by charleszhn** [comment]
感谢您的回复，csrediscore后续会有单元测试提供吗？因为版本改变了再用原来的单元测试是不是不太好，
`NU1107: 检测到 Microsoft.Extensions.Caching.Abstractions 存在版本冲突。直接从项目引用包可解决此问题。 
 GXT.Authorization -> Caching.CSRedis 2.3.9.1 -> Microsoft.Extensions.Caching.Abstractions (>= 2.1.1) 
 GXT.Authorization -> Microsoft.AspNetCore.App 2.1.0-rc1-final -> Microsoft.Extensions.Caching.Abstractions (= 2.1.0-rc1-final).
可以选择 csredis2.3.7
`

**Comment by 2881099** [comment]
是的，单元测试后续会有。

这个是 Caching.CSRedis 2.3.9.1 与 .netcore 版本冲突导致的错误，.net core 2.1 是长期稳定版本，建议跟着微软的升级步伐。

与本项目 CSRedisCore 无关哦，本项目是绿绝色无依赖，不出产生此版本冲突。

应该在这个项目内提问：
https://github.com/2881099/Microsoft.Extensions.Caching.CSRedis

感谢反馈，关闭了。
