### ISSUE TITLE
连接池的创建和复用

### ISSUE THREAD

**Issue by Newxml** [2881099/csredis#101]
现在有这样一个需求，有一个redis存取接口，执行两次， 第二次执行的时候，获取到第一次执行时的 connect_clients去执行存取，这个能实现嘛？

**Comment by 2881099** [comment]
是想打包执行是吗，StartPipe/Eval 都可以做到。
如果不用分区或集群，可以使用：

```csharp
using(var client = rds.MasterPool.Get()) {
   client.set("xxx", "1");
   client.get("xxx");
}
```

这是是用的同一链接

**Comment by Newxml** [comment]
非常感谢你的及时回答，并不是打包执行，而是一个接口可能会被多个客户端调用，我现在的做法是每一次执行接口都new了CSRedisClient ，在存取结束之后释放连接。我想多个客户端在不同时间调用接口的时候，使用同一个connect_clients执行存取。我现在很困惑。如何才能实现

**Comment by 2881099** [comment]
同连接给多个客户端使用，会导致并发写数据，或读数据错乱。

**Comment by 2881099** [comment]
CSRedisClient 多线程安全，RedisClient 多线程不安全。

**Comment by Newxml** [comment]
好的，感谢您的回答。我还是用我原来的方法 每次执行的时候new一个CSRedisClient 去操作。只要并发量小于10000 connect_clients不超过 10000就不会有问题了

**Comment by Newxml** [comment]
还有请问一下，你上面代码的rds是什么对象，我刚刚才接触redis，如果可以的话，可以写一个demo提供我学习一下嘛？843912592@qq.com

**Comment by 2881099** [comment]
rds 是 CSRedisClient 实例啊。

每次执行的时候new一个CSRedisClient 去操作，这个作法很浪费性能啊。CSRedisClient是单例而生，针对 一个库创建一次即可。

**Comment by Newxml** [comment]
刚刚不是说从不同客户端发来请求可能会导致并发，写数据，或读数据错乱。那要如何实现呢？
![image](https://user-images.githubusercontent.com/34527830/54003207-59d6ff80-418c-11e9-916f-e2110ff15108.png)
这是还需要引用什么嘛？

**Comment by 2881099** [comment]
定义一个全局 static CSRedisClient sd；
每来请求，都使用这个对象访问 redis，是安全可靠的；

是否能达到你的要求。

另外更改：using (var client = sd.Nodes.Frist().Value.Get())

**Comment by Newxml** [comment]
十分感谢作者耐心的回答。我去尝试一下。
