### ISSUE TITLE
订阅问题

### ISSUE THREAD

**Issue by scymen** [2881099/csredis#102]
订阅代码：
RedisHelper.Subscribe((RedisKey.GwStatusChannel, msg =>
            {
                Console.WriteLine(msg);
            }
            ));

3.0.40及更旧的版本，订阅时，会输出以下信息，功能正常，

正在订阅【127.0.0.1:6379/0】(channels:gw:status:chnl)/(chans:gw:status:chnl)

但是，

更新到了 版本 3.0.42 后，订阅时，输出以下信息，不知道是什么原因，Redis 是正常的，是不是发布端没有 publish 消息前，不可以订阅（订阅一个不存在的频道？）？

正在订阅【127.0.0.1:6379/0】(channels:gw:status:chnl)/(chans:gw:status:chnl)
订阅出错【127.0.0.1:6379/0】(channels:gw:status:chnl)/(chans:gw:status:chnl)：Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.，3秒后重连。。。
订阅出错【127.0.0.1:6379/0】(channels:gw:status:chnl)/(chans:gw:status:chnl)：Unexpected response type: MultiBulk (expecting Status)，3秒后重连。。。
订阅出错【127.0.0.1:6379/0】(channels:gw:status:chnl)/(chans:gw:status:chnl)：Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.，3秒后重连。。。
订阅出错【127.0.0.1:6379/0】(channels:gw:status:chnl)/(chans:gw:status:chnl)：Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.，3秒后重连。。。
订阅出错【127.0.0.1:6379/0】(channels:gw:status:chnl)/(chans:gw:status:chnl)：Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.，3秒后重连。。。
订阅出错【127.0.0.1:6379/0】(channels:gw:status:chnl)/(chans:gw:status:chnl)：Cannot write to a BufferedStream while the read buffer is not empty if the underlying stream is not seekable. Ensure that the stream underlying this BufferedStream can seek or avoid interleaving read and write operations on this BufferedStream.，3秒后重连。。。

**Comment by 2881099** [comment]
哦，你先使用41版本

42设置了 receivetimeout，默认值5秒没数据流就会保错

**Comment by 2881099** [comment]
这个设置影响订阅，是bug，谢谢反馈

**Comment by 2881099** [comment]
3.0.43 修复了这个 bug，测试通过

**Comment by scymen** [comment]
哦~好快！辛苦了，非常谢谢。

**Comment by 2881099** [comment]
之前有一个用户反馈，某网络情况下无限卡死，情况非常特殊。
所以改进了 ReceiveTimeout，然后订阅这边受到了影响。
