### ISSUE TITLE
csredis连接腾讯云redis2.8主从版失败

### ISSUE THREAD

**Issue by wgq4812** [2881099/csredis#107]
csredis连接腾讯云redis2.8主从版失败 ，尝试了很久  一直初始化失败，不知为什麽。

**Comment by wgq4812** [comment]
> csredis连接腾讯云redis2.8主从版失败 ，尝试了很久 一直初始化失败，不知为什麽。

通过静态类RedisHelper.Initialization 进行初始化 。然后各种失败。、

**Comment by 2881099** [comment]
方便的话加我的 qq 2881099，把连接串发给我尝试一下。

**Comment by wgq4812** [comment]
弄好了，原来是redis dll 版本问题，已经解决了。谢谢。
