### ISSUE TITLE
哨兵

### ISSUE THREAD

**Issue by trueYJlove** [2881099/csredis#110]
![1](https://user-images.githubusercontent.com/46584827/54598520-9e5b7880-4a73-11e9-90d9-0aaac8ce7cf7.png)
![2](https://user-images.githubusercontent.com/46584827/54598523-a0bdd280-4a73-11e9-93cd-c0cae23f2d54.png)
![3](https://user-images.githubusercontent.com/46584827/54598530-a3202c80-4a73-11e9-9282-8f2bd2450059.png)

哨兵模式下，连接得不到master

**Comment by 2881099** [comment]
请问你的redis版本是多少

**Comment by 2881099** [comment]
https://github.com/2881099/csredis/blob/b415ab314e25da8793135d6e796d2cc72ff634a2/src/CSRedisCore/Types.cs
406行，源码下载了调试一下这里。

估计个版本有关，这里读取不到。

**Comment by 2881099** [comment]
PendingCommands 试试忽略一下行不行

**Comment by trueYJlove** [comment]
好，我看看是不是版本问题，然后下载源码调试一下。感谢🙏

2881099 <notifications@github.com>于2019年3月19日 周二18:32写道：

**Comment by 2881099** [comment]
@trueYJlove 最终的结论有了吗。您使用的版本，以及断点调试的结果。

**Comment by trueYJlove** [comment]
您好，不好意思昨天提问题之后下班了，因为代码在公司机器上所以还没调试。等会去调试了反馈结果。谢谢跟进

2881099 <notifications@github.com>于2019年3月20日 周三07:56写道：

**Comment by 2881099** [comment]
这个问题提得非常及时，希望可以改进帮助到更多人，感谢反馈。

**Comment by trueYJlove** [comment]
您好，redis版本3.2.11。忽略掉406行可以。

2881099 <notifications@github.com>于2019年3月19日 周二18:32写道：

**Comment by 2881099** [comment]
谢谢反馈，我来修复这个问题。

**Comment by trueYJlove** [comment]
您看下，这是我这边redis查到的字段，是不是字段名称变了而您那个代码里面写死名称了。看看是不是这个问题

2881099 <notifications@github.com>于2019年3月20日 周三10:06写道：

**Comment by 2881099** [comment]
注释了不要紧，目前那几个属性没有被使用。
