### ISSUE TITLE
在windows服务中使用csredis，cpu 100%

### ISSUE THREAD

**Issue by micromouse** [2881099/csredis#111]
public class CSRedisHelper {
        private readonly string prefix;
        private readonly CSRedisClient csredis;

        /// <summary>
        /// 初始化CSRedisHelper
        /// </summary>
        /// <param name="dbNum">(可选)使用的数据库</param>
        public LYCSRedisHelper(int dbNum = 0) {
            prefix = “myapp”;
            var connectionString = "localhost,password=redis,allowAdmin=true,defaultDatabase=0";
            csredis = new CSRedisClient(connectionString);
        }

        /// <summary>
        /// 删除Hash键
        /// </summary>
        /// <param name="key">key</param>
        public void HashDelete(string key) {
            key = $"{prefix}{key}";
            csredis.HDel(key);
        }

        ......
   }

//untiy注入保证全局单例
var csRedisHelper = new CSRedisHelper(0);
IUnityContainer.RegisterInstance(typeof(LYCSRedisHelper), csRedisHelper)
启动windows服务什么也不做，一会儿cpu就100%了，相同的代码在winform中就运行正常

@2881099 群主能不能有空看下，多谢！

**Comment by 2881099** [comment]
现在在外地，要过两天才可以

先用winform过渡一下。

然后多打印日志，分析定位问题，如果我来也是这样做

**Comment by 2881099** [comment]
AppDomain.CurrentDomain.ProcessExit += (s1, e1) => {

};
Console.CancelKeyPress += (s1, e1) => {
};


监控下这两个事件的日志

**Comment by micromouse** [comment]
好的，多谢！

**Comment by micromouse** [comment]
@2881099 已经解决，

在ThreadPool.RegisterWaitForSingleObject执行的方法里出现了死循环，因为发布的windows服务缺少一个文件，最初的日志一直报redis超时，iocp超高。

通过逐步缩小范围，问题终于解决了，多谢 2881099 大大

**Comment by 2881099** [comment]
问题解决就好，你对技术钻研的精神值得佩服
