### ISSUE TITLE
setex这个命令有对应的吗

### ISSUE THREAD

**Issue by JOJOJOFran** [2881099/csredis#118]

**Comment by 2881099** [comment]
有，你试下，所有命令都有，与方法名一样

**Comment by JOJOJOFran** [comment]
这个你默认放到Set里面了吧 叶老板

**Comment by 2881099** [comment]
set 和外面都有

**Comment by JOJOJOFran** [comment]
> set 和外面都有

外面只找到SetNx ，没找到SetEx

**Comment by 2881099** [comment]
是的呢，重载了，功能是一样的。

刚才看成了setnx

**Comment by sdwdjzhy** [comment]
CSRedisClient  里边确实没有setex啊

**Comment by 2881099** [comment]
.Set("a", 1, 10)

> CSRedisClient 里边确实没有setex啊

**Comment by 2881099** [comment]
@sdwdjzhy http://doc.redisfans.com/string/set.html 看这里
