### ISSUE TITLE
怎样切换数据库 #

### ISSUE THREAD

**Issue by SpeakHero** [2881099/csredis#12]
怎么怎样切换数据库 #  多个数据库操作

**Comment by 2881099** [comment]
不建议一个 CSRedisClient 对象切换操作多个数据库，为什么呢？除非每次操作都做一次切换数据库操作，相当繁琐。

redis.Select(1);
redis.Set("key1", "1");

redis.Select(2);
redis.Get("key1");

------------------------------------------------

正确姿势 ：

CSRedisClient rc1 = new CSRedisClient("127.0.0.1:6379,password=,defaultDatabase=1,poolsize=10,ssl=false,writeBuffer=20480,prefix=xx");

CSRedisClient rc2 = new CSRedisClient("127.0.0.1:6379,password=,defaultDatabase=2,poolsize=10,ssl=false,writeBuffer=20480,prefix=xx");
