### ISSUE TITLE
使用SubscribeList实现消息队列时的一点小疑问

### ISSUE THREAD

**Issue by connself** [2881099/csredis#120]
我想实现一个List的消息队列，List有一个或多个就自动取出做相应的处理，SubscribeList方法使用起来没什么问题，但是默认设置了timeout=5，我改成timeout=0或者timeout>10时，调试输出日志会有异常，List里第一条好像也会丢失。

`
引发的异常:“System.IO.IOException”(位于 System.dll 中)
引发的异常:“System.IO.IOException”(位于 CSRedisNFX45.dll 中)
引发的异常:“CSRedis.RedisProtocolException”(位于 CSRedisNFX45.dll 中)
引发的异常:“System.ObjectDisposedException”(位于 System.dll 中)
引发的异常:“System.IO.IOException”(位于 System.dll 中)
引发的异常:“System.IO.IOException”(位于 CSRedisNFX45.dll 中)
引发的异常:“System.IO.IOException”(位于 CSRedisNFX45.dll 中)
引发的异常:“System.IO.IOException”(位于 System.dll 中)
引发的异常:“System.IO.IOException”(位于 CSRedisNFX45.dll 中)
引发的异常:“System.IO.IOException”(位于 CSRedisNFX45.dll 中)
线程 0xc60 已退出，返回值为 0 (0x0)。
`

**Comment by 2881099** [comment]
把你的初始化CSRedisClient的代码，以及连接字符串发出来一下，密码不用发。

然后把sublist的代码也发一下

**Comment by connself** [comment]
`var csredis = new CSRedisClient(“127.0.0.1:6379,password=123456”);
RedisHelper.Initialization(csredis );`

` var s = RedisHelper.SubscribeList("mq", (message) =>
{
 Console.WriteLine(" mq 订阅收到消息：" + message);
}`

 就这样简单的测试

**Comment by 2881099** [comment]
https://github.com/2881099/csredis/blob/master/README.md
看这里的参数，有一项SyncTimeout默认值是10秒，冲突了。

不建议改代码的等待秒数，5秒比较合适，如果改大了，需要配合SyncTimeout参数一起改

**Comment by 2881099** [comment]
小于等于0，也一样，相当于无限等待

**Comment by connself** [comment]
好的 了解了 🙏
