### ISSUE TITLE
请问怎么获取某个key下面的子key数量，详情请看内容

### ISSUE THREAD

**Issue by 5653325** [2881099/csredis#124]
您好。比如Redis中的Key的格式如下
TOP
- One
--Two
----B1
-----key1
-----key2
-----key3
----B2
-----key4
-----key5
----B3
--Three
请问有办法获取到Two下面的子节点的数量和Key名吗?(不包含B1 B2 B3下的子Key，就是返回数量是3，Key名是 B1 B2 B3）
谢谢！

**Comment by 2881099** [comment]
redis 对象层级只能支持到两级啊，就是 hash

先了解一下数据类型：http://redisdoc.com/

**Comment by 5653325** [comment]
好的，我用ZSet来曲线实现了
