### ISSUE TITLE
pub/sub有内存泄漏吗？

### ISSUE THREAD

**Issue by leigoCQ** [2881099/csredis#128]
pub/sub有内存泄漏吗？subscribe后，不停publish发现内存不断增大，之前用StackExchange.Redis没有这个问题，切换CSRedis后出现了

**Comment by 2881099** [comment]
能上几张图片吗，现在有点忙。订阅这块用了很久，没出现问题。

**Comment by leigoCQ** [comment]
![program](https://user-images.githubusercontent.com/47114616/57605187-ada10300-7598-11e9-98ff-0654c248169b.png)
![pub](https://user-images.githubusercontent.com/47114616/57605193-b0035d00-7598-11e9-8b7d-d990a3f54b39.png)
![sub](https://user-images.githubusercontent.com/47114616/57605202-b42f7a80-7598-11e9-86a6-b6d3f8140c21.png)
运行半个多小时后，内存又40多到现在的70多了。

**Comment by 2881099** [comment]
调用 RedisHelper.PublishNoneMessageId 试试

RedisHelper.Publish 会附带 msgId|消息体，并且对应的 Subscrible 会额外判断本消息是否被处理过。

存在消耗的情况。

然后 stackexchange.redis 因为没有这种机制处理，所以内存也稳定着。

**Comment by leigoCQ** [comment]
RedisHelper.PublishNoneMessageId也试过了，也试缓慢的增长，我再试下，感谢您的答复！

**Comment by 2881099** [comment]
好的，记住反馈结果

**Comment by leigoCQ** [comment]
剥离出来后发觉控件本身没问题，对自身程序对象进行了及时释放，问题已解决。
