### ISSUE TITLE
微软云redis，list异步 api  连接超时，同步api正常

### ISSUE THREAD

**Issue by ccccccmd** [2881099/csredis#130]
今天遇到一个很诡异得问题，List 的这两个异步api在本地测试环境redis没有问题，发布到正式环境出问题：

`RedisHelper.RPushAsync(que, msg);`

` RedisHelper.LPopAsync<T>(que);`

当时发现 ` RedisHelper.Set(a,b);` 是正常的，就把那两个api换成 同步 的api，发现可以push 和pop数据了

正式环境 ：微软云 Redis 版本 3.2.7  开着ssl

异常信息：
> Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
System.IO.IOException: Unable to read data from the transport connection: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond. ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)
   --- End of inner exception stack trace ---
   at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalarAsync[T](String key, Func`3 hande

**Comment by 2881099** [comment]
这是第一次使用后，azure出现的问题吗？

**Comment by ccccccmd** [comment]
之前基于StackExchange.Redis封装的helper操作这个redis实例
这次是用的csredis，用到的list 的那两个异步api 出问题了

**Comment by 2881099** [comment]
发布上线后，马上就出现了这个问题吗？

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/57995392-69f84d00-7af4-11e9-8f98-730dfc5e858d.png)
云服务器网络策略比较特殊，你试试加下这个参数，错误尝试的次数。

**Comment by 2881099** [comment]
idleTimeout=20000,tryit=1

在原有基础上，改下这个，poolsize=10，这个不需要设置太大

**Comment by 2881099** [comment]
基本上云服务器设置，都需要修改一下默认参数值。特别是 idleTimeout 这个，要设置成目标服务器断开连接策略值范围内，一般是1分钟不活跃就会断开连接。

这里设置为 20 秒比较合适。

**Comment by ccccccmd** [comment]
是的，我在本地调试，连azure的redis，首次调用 list 的异步api就抛异常， 但是调用同步的get, set是没问题的，不是实例连接不上。 我用你的方法再去尝试下

**Comment by 2881099** [comment]
异步，前面是否加了 await 或 .Wait()。

大体是上面说原因，通过配置可以解决。

**Comment by 2881099** [comment]
异步方法使用 AsyncSocketEventArgs，开启 ssl 后有影响，算是 bug
如果可以的话，关闭 ssl 功能，就正常了。

谢谢
