### ISSUE TITLE
redis初始化出错

### ISSUE THREAD

**Issue by ThomTan** [2881099/csredis#133]
运行环境：      .NetFramework 4.6.1 、Windows 2012 R2
NutGet版本： 3.0.55
异常问题：      初始化失败，异常卡死，请求连接字符串正常，其他服务器正常使用。

异常信息: System.IO.FileLoadException
   在 CSRedis.CSRedisClient..ctor(System.Func`2<System.String,System.String>, System.String[], System.String[])
   在 CSRedis.CSRedisClient..ctor(System.String)
   在 Plugin.CommonService.Common.Utility.RedisCommon.Init(System.String)
   在 FujicaSender.Wpf.App.OnStartup(System.Windows.StartupEventArgs)
   在 System.Windows.Application.<.ctor>b__1_0(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.DispatcherOperation.InvokeImpl()
   在 System.Windows.Threading.DispatcherOperation.InvokeInSecurityContext(System.Object)
   在 System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   在 System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   在 System.Windows.Threading.DispatcherOperation.Invoke()
   在 System.Windows.Threading.Dispatcher.ProcessQueue()
   在 System.Windows.Threading.Dispatcher.WndProcHook(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndWrapper.WndProc(IntPtr, Int32, IntPtr, IntPtr, Boolean ByRef)
   在 MS.Win32.HwndSubclass.DispatcherCallbackOperation(System.Object)
   在 System.Windows.Threading.ExceptionWrapper.InternalRealCall(System.Delegate, System.Object, Int32)
   在 System.Windows.Threading.ExceptionWrapper.TryCatchWhen(System.Object, System.Delegate, System.Object, Int32, System.Delegate)
   在 System.Windows.Threading.Dispatcher.LegacyInvokeImpl(System.Windows.Threading.DispatcherPriority, System.TimeSpan, System.Delegate, System.Object, Int32)
   在 MS.Win32.HwndSubclass.SubclassWndProc(IntPtr, Int32, IntPtr, IntPtr)
   在 MS.Win32.UnsafeNativeMethods.DispatchMessage(System.Windows.Interop.MSG ByRef)
   在 System.Windows.Threading.Dispatcher.PushFrameImpl(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Threading.Dispatcher.PushFrame(System.Windows.Threading.DispatcherFrame)
   在 System.Windows.Application.RunDispatcher(System.Object)
   在 System.Windows.Application.RunInternal(System.Windows.Window)
   在 System.Windows.Application.Run(System.Windows.Window)
   在 FujicaSender.Wpf.App.Main()

**Comment by 2881099** [comment]
.net framework 引用 netstandard 库需要

**Comment by 2881099** [comment]
System.IO.FileLoadException 错误是这个，说明引用缺少 dll

https://github.com/2881099/FreeSql/issues/51
可以参考这个，一样的解决办法试试

**Comment by 2881099** [comment]
NuGet 包的引用方式从 packages.config 升级为 PackageReference
