### ISSUE TITLE
未能加载文件或程序集System.ValueTuple

### ISSUE THREAD

**Issue by ThomTan** [2881099/csredis#134]
运行环境： .NetFramework 4.6.1 、Windows 2012 R2
NutGet版本： 3.0.55
System.IO.FileLoadException: 未能加载文件或程序集“System.ValueTuple, Version=0.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51”或它的某一个依赖项。找到的程序集清单定义与程序集引用不匹配。 (异常来自 HRESULT:0x80131040)

**Comment by ThomTan** [comment]
.NetFramework 4.6.1 版本
添加以下引用关系：
<assemblyBinding xmlns="urn:schemas-microsoft-com:asm.v1"> 
    <dependentAssembly> 
    <assemblyIdentity name="System.ValueTuple" publicKeyToken="cc7b13ffcd2ddd51" culture="neutral" /> 
    <bindingRedirect oldVersion="0.0.0.0-4.0.2.0" newVersion="4.0.2.0" /> 
    </dependentAssembly> 
</assemblyBinding>

**Comment by 2881099** [comment]
是的，和之前的解决方法一样
