### ISSUE TITLE
3.0.59版，使用BLPop，30秒左右报错

### ISSUE THREAD

**Issue by litesz** [2881099/csredis#138]
使用同步的阻塞等待命令，30秒左右报错，错误信息如下:System.IO.IOException: Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。. ---> System.Net.Sockets.SocketException: 由于连接方在一段时间后没有正确答复或连接的主机没有反 应，连接尝试失败。
   at System.Net.Sockets.NetworkStream.Read(Byte[] buffer, Int32 offset, Int32 size)

**Comment by 2881099** [comment]
看首页参数说明，大概设置 idleTimeout 可以解决，设置多大根据服务器网络环境，大概15秒差不多

**Comment by 2881099** [comment]
注意单位，毫秒

**Comment by litesz** [comment]
依旧无效
![图片](https://user-images.githubusercontent.com/24803206/58769610-0cc3c780-85db-11e9-88ec-563fceffe6b2.png)

**Comment by 2881099** [comment]
执行其他命令，正常吗？

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/58770002-af317a00-85de-11e9-92cd-aa35861bb5a7.png)

**Comment by 2881099** [comment]
阻塞30秒后，进入到了下面的断点

**Comment by litesz** [comment]
![图片](https://user-images.githubusercontent.com/24803206/58773999-0b51c980-85f2-11e9-8057-abfec78bc64e.png)
基础的命令执行正常，我现在降级到之前的5.0.35就能正常使用

**Comment by 2881099** [comment]
5.0.35？
3.0.35?

3.0.59，只有 BLPop 有上述问题，基础命令无问题？
59，和35，在这个命令上没有更改过，然后我刚才在本地测试没有出现上述问题。

希望可以提供更多可分析的原因

**Comment by litesz** [comment]
系统win10,vs2019,redis服务在本地
项目之前是3.0.35写的，升级后发现问题，之后将之前的测试用例升级至0.59，同样发生该问题
以下是测试用项目信息
![图片](https://user-images.githubusercontent.com/24803206/58774513-5e2c8080-85f4-11e9-9522-144054e72076.png)
![图片](https://user-images.githubusercontent.com/24803206/58774526-6b496f80-85f4-11e9-823a-88cb2cd17fb7.png)
还需要提供什么？

**Comment by litesz** [comment]
BLPop 在扔出异常前能正常获得数据，发生异常时，list中的数据同样会被移除

**Comment by 2881099** [comment]
BLPop 参数怎么传的，上面的截图被  cmd 遮挡住了

**Comment by litesz** [comment]
var result = RedisHelper.BLPop<int>(300, "test");

**Comment by 2881099** [comment]
是不是被防火墙干掉了，300有点长。

为啥不适合设长？

程序退出时，需要等待这个300秒执行完成，因为线程一直在阻塞，无法退出。
不确定您的使用场景，但可以分多次等待。

for (var a = 5; a < 305 && 程序未退出, a += 5) {
   BLPop(5, "test");
}

**Comment by 2881099** [comment]
如果为了做订阅消息功能，可以使用 RedisHelper.SubscribeList，这个方法是 BLPop + Push 的封装。

**Comment by litesz** [comment]
关防火墙没用。
谢谢你的建议，我现在按你说的方法改了下代码，目前测试下来没问题。
