### ISSUE TITLE
CacheShell关于getdata的判断

### ISSUE THREAD

**Issue by Yuyg77** [2881099/csredis#139]
getdata()获取数据时，可以优化判断一下，数据源是不是为null，现在的情况是，如果数据源为null，会直接序列化成字符串“null”，再次获取时，不会正常获取新的数据源。
![微信截图_20190603203246](https://user-images.githubusercontent.com/26400716/58802075-d029b780-863e-11e9-801f-ec98c17b298b.png)
![微信截图_20190603203301](https://user-images.githubusercontent.com/26400716/58802078-d029b780-863e-11e9-85b9-87adcb98147b.png)

**Comment by 2881099** [comment]
这个是特意做的，防止缓存击穿

**Comment by 2881099** [comment]
这理有优化空间，为null时缓存时间可以少一些。谢谢反馈
