### ISSUE TITLE
速度有些慢

### ISSUE THREAD

**Issue by gwhzh21** [2881099/csredis#143]
我拿测试的代码和StackExchange.Redis 1.2.6还有NewLife.Redis 3.2.7093.338
.net framwrok 4.5.2 下使用
![image](https://user-images.githubusercontent.com/17920677/59572692-6b139e80-90e1-11e9-8da6-379d837ffe70.png)
有什么办法提升速度?

**Comment by gwhzh21** [comment]
补充一下，我用的是redis-windows 3.2.100.

**Comment by 2881099** [comment]
运行在 .net core 下可以提升，.net framework 没有特别测试过
