### ISSUE TITLE
使用eval的疑问

### ISSUE THREAD

**Issue by ding-s-p** [2881099/csredis#147]
官方文档中eval使用时多key多arg，这边的接口是一个key多个arg，当遇到需要多个key的时候怎么处理，使用阿里云redis，就有这个限制：
![image](https://user-images.githubusercontent.com/30709795/60249770-100b5400-98f8-11e9-888a-bc8fc6861d59.png)

**Comment by 2881099** [comment]
我只放开一个 key 是为了分区/集群定位，多 key 时在集群下执行会报错

多 key 可以字符串传入。
```csharp
RedisHelper.Eval("key1", $"redis.call('del', KEYS[1], '{key2}')")
```

**Comment by ding-s-p** [comment]
> 我只放开一个 key 是为了分区/集群定位，多 key 时在集群下执行会报错
> 
> 多 key 可以字符串传入。
> 
> ```cs
> RedisHelper.Eval("key1", $"redis.call('del', KEYS[1], '{key2}')")
> ```

没太看明白您的意思，接口格式不是Eval(string script, string key, params object[] args)吗？为啥key会在第一位，脚本在第二位？

**Comment by 2881099** [comment]
不好意思，发的是伪代码，位置错了。
意思了解就好，为了分区集群冲突。
其他keys可通过字符串传入，或者ARGV传入也行。
