### ISSUE TITLE
连接的地址，与实际提供的地址不一样

### ISSUE THREAD

**Issue by sofuny** [2881099/csredis#148]
![image](https://user-images.githubusercontent.com/15317714/60312693-dafe1080-998e-11e9-8939-87514c20b1db.png)
这个是我提供的地址
![image](https://user-images.githubusercontent.com/15317714/60312720-ef420d80-998e-11e9-883f-8551e61eb04f.png)
但实际访问的地址却是这个，数据也保存到这个地址去了，这是为什么呢？

**Comment by sofuny** [comment]
提供的是两个单点的redis地址

**Comment by 2881099** [comment]
你是用的哨兵？

还有 sendip 怎么是两个 ip

**Comment by sofuny** [comment]
两个单点的，其实也只是为了测试是连接成功还是连接到其中一个点，但发现都不是

**Comment by 2881099** [comment]
所以是传错了啊，两个单点，定义两个 CSRedisClient 便是

**Comment by sofuny** [comment]
我以为会提示连接串异常，但调试是连接到6379的redis去了

**Comment by 2881099** [comment]
6379 是因为后面 int.Parse 失败

**Comment by sofuny** [comment]
好的，我做一下地址的校验
