### ISSUE TITLE
CSRedisCache来源

### ISSUE THREAD

**Issue by fayuanliu** [2881099/csredis#15]
//注册mvc分布式缓存
            services.AddSingleton<IDistributedCache>(new Microsoft.Extensions.Caching.Redis.CSRedisCache(RedisHelper.Instance));
这个 CSRedisCache指的是什么，从哪里来的呢，求解一下，谢谢！

**Comment by 2881099** [comment]
nuget 搜索 Caching.CSRedis

**Comment by fayuanliu** [comment]
谢谢，明白了！

发送自 Windows 10 版邮件<https://go.microsoft.com/fwlink/?LinkId=550986>应用

________________________________
发件人: 2881099 <notifications@github.com>
发送时间: Monday, August 6, 2018 7:09:33 PM
收件人: 2881099/csredis
抄送: fayuaniu; Author
主题: Re: [2881099/csredis] CSRedisCache来源 (#15)


nuget 搜索 Caching.CSRedis

―
