### ISSUE TITLE
关于SetNx方法

### ISSUE THREAD

**Issue by yjqGitHub** [2881099/csredis#16]
好像没有把SetNx的方法暴露出来

**Comment by yjqGitHub** [comment]
能不能把原先的所有方法都暴露出来 或者把RedisClient 这个对象暴露出来

**Comment by 2881099** [comment]
这个可以用，你现在用的是 RedisHelper 吗？有好的建议可以PR上来，谢谢。

**Comment by yjqGitHub** [comment]
我是用的是
new CSRedisClient(connection);
然后利用这个对象去获取信息，我这边自己管理了连接池

**Comment by yjqGitHub** [comment]
因为我需要这个方法去实现redis分布式锁 所以没办法，需要麻烦您帮忙把这些方法暴露一下

**Comment by yjqGitHub** [comment]
![image](https://user-images.githubusercontent.com/15052182/44318008-a06e4200-a466-11e8-90c0-bc7443996c5c.png)
这边利用线程安全的字典类管理了连接池，因为涉及到可能会使用到多个redis对象

**Comment by yjqGitHub** [comment]
还有一点就是我在看的时候，发现hash对字节数组的设置兼容好像还需要自己转为字符串，我这边使用了protobuf作为序列化

**Comment by 2881099** [comment]
```lua
ARGV[1] = redis.call('exists', 'aaa')
if ARGV[1] ~= '1' then
   return redis.call('set', 'aaa', '1')
end
return 0
```

SetNx 的现实方法

**Comment by 2881099** [comment]
(RedisHelper 或 CSRedisClient) .Set("aaa", "1", -1, CSRedisExistence.Nx);

更新 CSRedisCore 2.3.9.3

**Comment by yjqGitHub** [comment]
好的  多谢 麻烦了
