### ISSUE TITLE
Connection was not opened on startup

### ISSUE THREAD

**Issue by sunliusi** [2881099/csredis#164]
应用启动瞬间，报CSRedis.RedisClientException: Connection was not opened
初步定位：启动瞬间，15tps的并发请求，redis连接未初始化完成

启动完成后，未出现此异常

**Comment by 2881099** [comment]
你说的tps是接口的请求量吗？

**Comment by sunliusi** [comment]
是的，启动瞬间的请求量

**Comment by 2881099** [comment]
有预热连接池吗，preheat

**Comment by sunliusi** [comment]
连接串如下：
defaultDatabase=0,poolsize=50,preheat=20,connectTimeout=15000

preheat不设置，也报错
