### ISSUE TITLE
替换Newtonsoft.Json版本是否有问题？

### ISSUE THREAD

**Issue by lukejian** [2881099/csredis#165]
你好，由于和项目中其他框架的冲突（.NET 4.5环境），我最高只能引用Newtonsoft.Json 11.0.2版本，但是CSRedisCore 3.1.5 要求Newtonsoft.Json大于12.0.2版本，我下载了源码，然后降低了Newtonsoft.Json的版本为11.0.2 ，初步测试下是可以使用的。我想请教下我降低版本是否有潜在的风险什么的？

**Comment by 2881099** [comment]
没问题

**Comment by lukejian** [comment]
好的，谢谢！
