### ISSUE TITLE
LPushAsync 在linux出現異常

### ISSUE THREAD

**Issue by platstar** [2881099/csredis#166]
使用gatling压测试时遇到一个状况

程序同时布在windows 2016 , centro os
通过 LPushAsync 将数据写入至REDIS
windows 在 request/sec 5000时很顺利的处理完
但centro os 的版本则是容易出现time out 
除了os端参数的调整外, 不知有没有什么建议或排错方向

Proto Recv-Q Send-Q Local Address           Foreign Address         State
tcp6     168      0 10.140.0.108:80         10.140.0.56:57272       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57632       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57352       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57235       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57160       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57142       ESTABLISHED
tcp6       0      0 10.140.0.108:80         10.140.0.56:59096       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57266       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57625       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57645       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57626       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57297       ESTABLISHED
tcp6       0      0 10.140.0.108:80         10.140.0.56:59076       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57305       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57242       ESTABLISHED
tcp6     168      0 10.140.0.108:80         10.140.0.56:57469       ESTABLISHED

**Comment by 2881099** [comment]
time out的错具体信息发一下

**Comment by platstar** [comment]
# gatling
nection timed out: /10.140.0.108:80
18:07:57.265 [WARN ] i.g.h.a.ResponseProcessor - Request 'step1: create fixed package' failed: j.n.ConnectException: connection timed out: /10.140.0.108:80
18:07:57.265 [WARN ] i.g.h.a.ResponseProcessor - Request 'step1: create fixed package' failed: j.n.ConnectException: connection timed out: /10.140.0.108:80
18:07:57.265 [WARN ] i.g.h.a.ResponseProcessor - Request 'step1: create fixed package' failed: j.n.ConnectException: connection timed out: /10.140.0.108:80
18:07:57.281 [WARN ] i.g.h.a.ResponseProcessor - Request 'step1: create fixed package' failed: j.n.ConnectException: connection timed out: /10.140.0.108:80
18:07:57.281 [WARN ] i.g.h.a.ResponseProcessor - Request 'step1: create fixed package' failed: j.n.ConnectException: connection timed out: /10.140.0.108:80

# aspnetcore: Microsoft.AspNetCore.Server.Kestrel.txt

2019-08-21 18:08:02.0117|Info|Connection id "0HLP62G0Q3JVQ", Request id "0HLP62G0Q3JVQ:00000001": the application completed without reading the entire request body.|
2019-08-21 18:08:02.0117|Info|Connection id "0HLP62G0Q3JOC", Request id "0HLP62G0Q3JOC:00000001": the application completed without reading the entire request body.|
2019-08-21 18:08:02.0127|Info|Connection id "0HLP62G0Q3K4K", Request id "0HLP62G0Q3K4K:00000001": the application completed without reading the entire request body.|
2019-08-21 18:08:02.0127|Info|Connection id "0HLP62G0Q3JVR", Request id "0HLP62G0Q3JVR:00000001": the application completed without reading the entire request body.|
2019-08-21 18:08:02.0127|Info|Connection id "0HLP62G0Q3JOE", Request id "0HLP62G0Q3JOE:00000001": the application completed without reading the entire request body.|

**Comment by 2881099** [comment]
加大连接池poolsize，加大Task线程池

再试试

**Comment by platstar** [comment]
晚回了, 找到問題了,跟組件無關
原因是上次在linux用AspNetCoreHostingModel:OutOfProcess 要改成InProcess
