### ISSUE TITLE
Redis服务器出现异常后，使用GetAsync方法有问题

### ISSUE THREAD

**Issue by pleasecallmemaoxian** [2881099/csredis#169]
复现步骤：关闭Redis服务器，使程序无法连接redis服务器，然后使用GetAsync方法去获取数据，不会抛出异常，但是会导致线程卡死。同步方法没有这个问题

**Comment by vl00** [comment]
好像所有的XXXAsync方法都有这个问题，我想到临时解决方法是
1. 用同步方法
2. Task.Factory.StartNew(()=>同步方法());

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/64876109-08e71d00-d681-11e9-9ec9-2085f9011624.png)
这样写测试不出你们说的情况，这样测对吗？

**Comment by pleasecallmemaoxian** [comment]
> ![image](https://user-images.githubusercontent.com/16286519/64876109-08e71d00-d681-11e9-9ec9-2085f9011624.png)
> 这样写测试不出你们说的情况，这样测对吗？

![image](https://user-images.githubusercontent.com/13816653/64877563-439e8480-d684-11e9-8284-47cedce4f7e4.png)

刚好还没睡，打开电脑写了段测试的代码

这是我测试的代码，正式环境是webapi的，不太方便截图，不过测试的效果是一样的，请帮忙看下是否有问题

**Comment by 2881099** [comment]
这段测试要启动redis-server吗

> > ![image](https://user-images.githubusercontent.com/16286519/64876109-08e71d00-d681-11e9-9ec9-2085f9011624.png)
> > 这样写测试不出你们说的情况，这样测对吗？
> 
> ![image](https://user-images.githubusercontent.com/13816653/64877563-439e8480-d684-11e9-8284-47cedce4f7e4.png)
> 
> 刚好还没睡，打开电脑写了段测试的代码
> 
> 这是我测试的代码，正式环境是webapi的，不太方便截图，不过测试的效果是一样的，请帮忙看下是否有问题

**Comment by pleasecallmemaoxian** [comment]
我没有启动

**Comment by 2881099** [comment]
@pleasecallmemaoxian 试出来了，有个变量状态未执行到，现在发布 3.1.6 版本，有空试下

**Comment by pleasecallmemaoxian** [comment]
好的，谢谢
