### ISSUE TITLE
高并发大负载时Set成功但是Get数据为空

### ISSUE THREAD

**Issue by mushichris** [2881099/csredis#172]
如题，调用同步方法将大量数据保存至Redis，Set方法并未返回false，且当前线程可以读到，但另一线程很快读取会出现偶尔读不到的情况（Get返回null），而且加了延时还是读不到
并发大约100，每个并发写入数据大约1.5M字符串（对900KB文件做Base64后的值），本机调试，redis已关闭持久化
连接参数："RedisConnection": "127.0.0.1:6379,poolsize=500,preheat=500,tryit=3"
其中poolsize分别测试过1,10,50,100,200,,500，均有同样情况
SET线程：
`                _redisManager.Instance.Set("File_" + history.FileId, Convert.ToBase64String(fileBytes), 600);
                while (string.IsNullOrEmpty(_redisManager.Instance.Get("File_" + history.FileId)))
                {
                    _redisManager.Instance.Set("File_" + history.FileId, Convert.ToBase64String(fileBytes), 600);
                }`
………………………………………………
………………………………………………
GET线程：
`                var fileBase64 = _redisManager.Instance.Get("File_" + fileId);
                _redisManager.Instance.Del("File_" + fileId);
                if (string.IsNullOrEmpty(fileBase64))
                {
                    return Ok((int)ErrorCode.服务器上未找到文件);
                }
`
两个线程是前后执行的，因为SET线程会把结果返回给客户端，客户端处理后再次请求GET线程所在接口。

**Comment by 2881099** [comment]
连接的服务器和key确定是一制的吗

**Comment by mushichris** [comment]
确定的，服务器是单机没做集群，key也确定是一致的，因为这个问题在负载小的时候不会出现，只在并发高的时候出现

**Comment by 2881099** [comment]
Get线程怎么有Del逻辑，是不是被删除了

**Comment by mushichris** [comment]
是先取出来之后删除的，避免内存占用过大

**Comment by 2881099** [comment]
当前线程能读到，其他线程读不到。

线程顺序问题啊

Del这样用也有并发问题，Get时没有，Del时可能有。

**Comment by mushichris** [comment]
实在不好意思，经过排查是业务系统的问题，并发高了会出现一个key请求2次的情况，因为删了第二次就取不到值了，感谢感谢，csredis是我用过最好的redis库，给大佬添麻烦了

**Comment by 2881099** [comment]
谢谢支持和肯定，大家都是贡献者。
