### ISSUE TITLE
如何知道redis连接建立成功了。

### ISSUE THREAD

**Issue by siegrainwong** [2881099/csredis#173]
现在的场景是我用redis实现了一个消息队列，如果redis挂了也要保证能走本地队列，怎么才能知道redis挂了连不上了？

**Comment by 2881099** [comment]
是普通节点吗？如果是比较简单：RedisHelper.Instance.Nodes[0].IsAvailable

如果是多节点，集群，Nodes 相当于正在使用的节点，每个节点都有可用状态的状态。

**Comment by 2881099** [comment]
或者在 RedisHelper 的操作方法捕捉异常

**Comment by siegrainwong** [comment]
好的，非常感谢。
