### ISSUE TITLE
多集群配置

### ISSUE THREAD

**Issue by CsharpLeague** [2881099/csredis#177]
请问多集群配置节怎么写,用；分隔吗，比如这样<add key="RedisHostConnection" value="172.16.224.165:7011;172.16.224.163:7011" />

**Comment by 2881099** [comment]
var csredis = new CSRedis.CSRedisClient(null,
  "127.0.0.1:6371,password=123,defaultDatabase=11,poolsize=10", 
  "127.0.0.1:6372,password=123,defaultDatabase=12,poolsize=11",
  "127.0.0.1:6373,password=123,defaultDatabase=13,poolsize=12",
  "127.0.0.1:6374,password=123,defaultDatabase=14,poolsize=13");

var csredis = new CSRedis.CSRedisClient("127.0.0.1:6379,password=123,defaultDatabase=13,prefix=key前辍");

这两种都可以，下面只需要指定任何一个可用的节点就行，上面的指定多个可用节点

**Comment by CsharpLeague** [comment]
好的谢谢
