### ISSUE TITLE
请问异常日志怎么打印出来

### ISSUE THREAD

**Issue by CsharpLeague** [2881099/csredis#181]
每次快到晚上12点CPU就爆满，抓取dump：000000000ebbd210 000007fe97c5839e CSRedisCore.dll!Unknown  显示这个，想看这时候的异常日志 不知道在哪配置

**Comment by 2881099** [comment]
大概是什么环境运行，每晚12点cpu爆满

**Comment by CsharpLeague** [comment]
两台12核CPU 24G内存 负载  双集群Redis  .net framework4.5  我个人感觉线程池的线程不够 每次从任务管理器查看的时候 线程都100多，poolsize用的默认的，我没有设置

**Comment by 2881099** [comment]
不设置默认是50个
用的异步方法吗，cpu慢的时候每秒多少次访问

**Comment by CsharpLeague** [comment]
300

**Comment by CsharpLeague** [comment]
现在肯定能定位到是redis原因 但是具体什么原因  不知道怎么输出日志

**Comment by CsharpLeague** [comment]
之前用的ServiceStack.Redis 就是一直超时 最近才换的CSRedis

**Comment by 2881099** [comment]
定位是redis-server服务器，还是CSRedisCore客户端

**Comment by CsharpLeague** [comment]
客户端，因为别的站点用着一直没事

**Comment by 2881099** [comment]
Redis 有一个实用的slowlog功能，正如你可以猜到的，可以让你检查运行缓慢的查询。

Slowlog 将会记录运行时间超过Y微秒的最后X条查询. X 和 Y 可以在 redis.conf 或者在运行时通过 CONFIG 命令: 

CONFIG SET slowlog-log-slower-than 5000
CONFIG SET slowlog-max-len 25
slowlog-log-slower-than 是用来设置微秒数的, 因此上面的设置将记录执行时间超过5秒的查询. 要获取记录的日志，你可以使用 SLOWLOG GET X 命令, 这里 X 是你想要获取的记录条数:

SLOWLOG GET 10



服务器试试这个
客户端 poolsize 加大设置为 500，preheat=20

**Comment by CsharpLeague** [comment]
好的 我试试 感谢
