### ISSUE TITLE
重连次数跟连接的超时时间可否提供配置？

### ISSUE THREAD

**Issue by siegrainwong** [2881099/csredis#183]
我现在在用EasyCaching的HybridCacheProvider做缓存层，然后Redis的Driver是用的CSRedisCore，如果我先关掉Redis，再开启应用程序进行请求，第一个请求会在长达20s后才响应。

期间会间隔数秒出现这样的日志：
Connection was not opened，3秒后重连。。。

我看了下这好像是您写死在代码里的，能否开放一个配置给这个连接的的超时时间和重试次数呢？
谢谢。

**Comment by 2881099** [comment]
你是不是用的订阅，订阅是这样的输出

**Comment by siegrainwong** [comment]
对的，前面有订阅的字样。

**Comment by 2881099** [comment]
这个是独立线程背后执行的，3秒不需要改吧，这样简单些。

**Comment by 2881099** [comment]
20秒的问题，和预热有关，还有一个参数testcluster，如果不是集群把它设置为false。

默认连接超时时间是5秒，出现的20秒时因为执行了几个命令，ping，还有在上面说到testcluster

**Comment by siegrainwong** [comment]
谢谢提示。
