### ISSUE TITLE
从.net core 2.2升级3.0后，连接报错

### ISSUE THREAD

**Issue by mw248** [2881099/csredis#187]
把项目从.net core 2.2升级3.0后，Redis连接报错

报错日志：状态不可用，等待后台检查程序恢复方可使用。ERR invalid password
DEBUG调试时，看到的exception message是：Unexpected end of stream; expected type 'Bulk'; data = ''
实际上密码并没有错，阿里云的Redis服务，未做任何变化，也并未修改密码，其它工具可以连接上

**Comment by mw248** [comment]
使用的是nuget最新版本的csrediscore

**Comment by 2881099** [comment]
在本地用 console 项目测试一下看。提示的错误是 redis-server 返回的密码错误。是不是配置文件读取了

**Comment by mw248** [comment]
被阿里云的报错信息迷惑了，最后发现原因是未把IP配置在白名单里
