### ISSUE TITLE
TTL 返回类型问题

### ISSUE THREAD

**Issue by scymen** [2881099/csredis#188]
redisHelper TTL 方法返回的类型为 long，当我尝试将某个KEY的过期时间，同步到其他KEY时，redisHelper.expire 方法传入参数为 int ,多了一步转换 long -> int 。

如果这两个参数类型设置一致是否更方便些？

不是BUG，只是建议，谢谢。

**Comment by 2881099** [comment]
本身是否想返回int的，但ttl有可能返回long的情况，因为不是所有expire都在csrediscore上执行的。

expire参数为int，使用起来比long方便，不需要每次转换类型。

所以矛盾没统一
