### ISSUE TITLE
Unable to read data from the transport connection

### ISSUE THREAD

**Issue by yiluxiaozhan** [2881099/csredis#189]
使用BRPop时，timeout设置为10或以上会报错，代码如下：
`CSRedisClient redisDB = new CSRedisClient("127.0.0.1:6379,connectTimeout=20000,defualtDatabase=0");
            RedisHelper.Initialization(redisDB);
            while (true)
            {
               var result = RedisHelper.BRPop(10, "tasklist");
                if(result != null)
                {
                    Console.WriteLine(result);
                }
            }`
报错信息：System.IO.IOException:“Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.”

**Comment by 2881099** [comment]
是不是redis服务器不支持这么久。

**Comment by yiluxiaozhan** [comment]
这个需要在哪可以配置？

**Comment by 2881099** [comment]
redis.conf timeout配置
或者防火墙设置，有些不支持长连接过久不活跃

**Comment by yiluxiaozhan** [comment]
redis.conf ：
# Close the connection after a client is idle for N seconds (0 to disable)
timeout 0

这个超时配置没有问题吧？

**Comment by 2881099** [comment]
没问题，那可能出在防火墙了

**Comment by yiluxiaozhan** [comment]
防火墙已经关了，还是会出现

**Comment by 2881099** [comment]
忘了有这个参数，syncTimeout参数值设置大一些试试，默认是10秒。见CSRedis项目首页

**Comment by yiluxiaozhan** [comment]
确实这个原因，谢谢。

**Comment by RoinBi** [comment]
> 确实这个原因，谢谢。

你设置了多少时间，我也遇到这个问题

**Comment by 2881099** [comment]
> > 确实这个原因，谢谢。
> 
> 你设置了多少时间，我也遇到这个问题

等待的时候，5-10 秒间比较合适

**Comment by RoinBi** [comment]
我看首页默认是10秒，指的是我在连接字符串中不配置，直接默认10秒吗？
![Uploading image.png…]()

**Comment by 2881099** [comment]
那就小于10秒吧 

> 我看首页默认是10秒，指的是我在连接字符串中不配置，直接默认10秒吗？
