### ISSUE TITLE
建议新增个RedisHelper.Set<T>(string key,T obj)，RedisHelper.Get<T>(string key)

### ISSUE THREAD

**Issue by xueshaoyu** [2881099/csredis#19]
建议新增个RedisHelper.Set<T>(string key,T obj)方法，里面进行序列化封装。

**Comment by 2881099** [comment]
谢谢反馈，但是不想加，担心很多新人问序列化的错误问题，增加解释成本。

目前项目无任何库引用依赖，“绿色“项目。

见谅。

**Comment by ly-hyaline** [comment]
private static Func<object, string> _serialize;
	private static Func<string, Type, object> _deserialize;
	private static Func<object, string> Serialize {
		get {
			if (_serialize == null) throw new Exception("使用前请初始化 RedisHelper.Initialization");
			return _serialize;
		}
	}
	private static Func<string, Type, object> Deserialize {
		get {
			if (_deserialize == null) throw new Exception("使用前请初始化 RedisHelper.Initialization");
			return _deserialize;
		}
	}
其实作者写的这个东西就很好，使对象与string转换无依赖；现在只应用用在了缓存壳上
