### ISSUE TITLE
Watch我好像没有找到

### ISSUE THREAD

**Issue by sliyufei** [2881099/csredis#190]
我找到了管道方法，看到主要是redis的基本事务。我现在想弄个乐观锁。。希望有个Watch命令，多谢大佬

**Comment by 2881099** [comment]
管道不是事务，事务默认没开放，如有必要这样使用：

using (var rc = RedisHelper.Instance.Nodes.First().Value.Get())

rc.Value.Watch 这里有 redisserver 2.8所有命令方法，记得用 using 包括起来使用。

**Comment by sliyufei** [comment]
多谢大佬，这么晚还回复我。辛苦辛苦。不过我可以请教您一下吗？

**Comment by sliyufei** [comment]
多谢大佬，这么晚还回复我。辛苦辛苦。不过我可以请教您个问题吗？
那您实现的管道不是用事务包起来的？是一条一条执行的吗？

**Comment by 2881099** [comment]
不是一条一条，管道是客户端技术，客户端csredis缓冲命令，最后打包为一个数据包发送给redis，减少网络往返次数。

**Comment by sliyufei** [comment]
好的 多谢大佬解惑。希望大佬有时间了把事务开启一下并且把watch方法放到外面来，真的很常用  谢谢。
