### ISSUE TITLE
通过RedisHelper.Instance.Nodes.First().Value.Get()拿到的实例部分命令不好用

### ISSUE THREAD

**Issue by sliyufei** [2881099/csredis#191]
如下图，Watch Multi 都正确返回了OK，但是下面的get 和set 命令无法使用。
![QQ浏览器截图20191020191124](https://user-images.githubusercontent.com/30107690/67158746-71a37280-f36e-11e9-98e1-531aa58631a0.png)

**Comment by 2881099** [comment]
RedisHelper.Get 使用了其他连接，所以总 rc.Value.Get试试？

**Comment by sliyufei** [comment]
不好意思没看明白，上面截图的意思是 rc.Value.Get取到的值是Null，但实际是有值的。但是我需要用事务，所以用rc来操作redis

**Comment by 2881099** [comment]
data的值什么时候写入的，怎么读不到值

**Comment by 2881099** [comment]
rc.Value.Get其他key试试

**Comment by sliyufei** [comment]
data的值我是用xshell 用命令写入的，我刚才使用xsell新开启了一个终端，也能够读到值。
其他key 我刚才测试了一下，也无法读取

**Comment by sliyufei** [comment]
写入key的时间是我在运行程序之前

**Comment by sliyufei** [comment]
我这里稳定复现，您可以试试

**Comment by 2881099** [comment]
其实为什么不直接用 Incr 命令

**Comment by sliyufei** [comment]
那只是我想模拟的一个乐观锁场景，先读后存。。

**Comment by 2881099** [comment]
开启 multi 事务后，是读不到数据的。 get 命令进行了队列，最终 exec 才会返回。

![image](https://user-images.githubusercontent.com/16286519/67160565-d4a00400-f384-11e9-9d86-0febbc6d6cb1.png)

**Comment by sliyufei** [comment]
想起来了。。。对不起 打扰了。非常感谢大佬得耐心解释
