### ISSUE TITLE
SubscrSubscribeListBroadcastibe-（非争抢）有办法关闭的时候把自己的订阅取消么

### ISSUE THREAD

**Issue by ligengrong** [2881099/csredis#193]
SubscrSubscribeListBroadcastibe-（非争抢）有办法关闭的时候把自己的定于取消么
例如：A（用户）程序启动，订阅 clientIdA，B（用户）程序启动，订阅clientIdB，再关闭程序可以同时把A、B的订阅取消么？ 谢谢！

**Comment by 2881099** [comment]
没明白，这个是广播订阅，大家都能收到。

**Comment by ligengrong** [comment]
已经知道怎么解决了，谢谢大神
