### ISSUE TITLE
BLPop超时之后不返回null，而是过很久之后直接抛出异常

### ISSUE THREAD

**Issue by jhy871167495** [2881099/csredis#204]
. var redisIP = "127.0.0.1";
. var redisPort = 6379;
. var redisPassword = "";
. CSRedis.CSRedisClient redisClient = new CSRedis.CSRedisClient($"{redisIP}:{redisPort},password={redisPassword},defaultDatabase=0,prefix=");
. redisClient.BLPop(5000, new string[] { "save_message" });

csreids 错误【127.0.0.1:6379/0】：无法从传输连接中读取数据: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。。    在 CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   在 CSRedis.CSRedisClient.NodesNotSupport[T](String[] keys, T defaultValue, Func`3 callback)
   在 CSRedis.CSRedisClient.BLPop(Int32 timeout, String[] keys)
   在 Submission#37.<<Initialize>>d__0.MoveNext()

**Comment by 2881099** [comment]
这个错误时socket报的，连接串 syncTimeout 默认是10秒，没数据返回就是报这个错误。

试试加大这个设置，或者控制 brpop 超时参数在10秒以内。

**Comment by jhy871167495** [comment]
好的，是我参数填错了，我以为超时参数是毫秒的

**Comment by Laifang** [comment]
> 这个错误时socket报的，连接串 syncTimeout 默认是10秒，没数据返回就是报这个错误。
> 
> 试试加大这个设置，或者控制 brpop 超时参数在10秒以内。

@2881099 
有办法修改 这个默认的超时时间吗

**Comment by 2881099** [comment]
连接串设置 syncTimeout
