### ISSUE TITLE
HMSet的参数该怎么调用？参数是键值对，不应该出现奇数(数量)

### ISSUE THREAD

**Issue by ColdwindY** [2881099/csredis#205]
错误：Message=keyValues 参数是键值对，不应该出现奇数(数量)，请检查使用姿势。
下面的代码
      Dictionary<string , object> dc = new Dictionary<string, object>();
      rdsds = new CSRedis.CSRedisClient("127.0.0.1:6379,poolsize=2,name=RedisTc1");
      for(int i=0;i<5; i++)
      {
        var time = DateTime.Now.ToString("yyyy-MM-dd HH:mm:ss.fff");
        dc.Add($"k{i}",time);
      }
      rds.HMSet("hs",dc);
HMSet出错Message=keyValues 参数是键值对，不应该出现奇数(数量)，请检查使用姿势。
怎么调用才是正确的？

**Comment by 2881099** [comment]
dc.Select(a=>new object[] { a.Key, a. Value }).SelectMany(a=>a).ToArray()

**Comment by ColdwindY** [comment]
test OK!
