### ISSUE TITLE
使用哨兵模式，切换Master服务后，不会对新Master服务添加订阅

### ISSUE THREAD

**Issue by quickappdev** [2881099/csredis#207]
环境版本：
CSRedisCore版本：3.1.13
windows 10系统 
.net framework 4.0
redis使用哨兵模式 1主3从2哨兵
主：192.168.1.6:6377
从：192.168.1.3:6375
问题：
项目使用哨兵模式，程序启动后添加订阅，然后把主服务停掉，待几秒提示切换到新的Master服务上，这时一直提示对新Master服务添加订阅出错。然后也收不到订阅消息。
![image](https://user-images.githubusercontent.com/37727233/68448358-3afaa280-021e-11ea-9b12-bc3c18a7e392.png)

简单调试了一下代码，发现切换Master后，csredis订阅逻辑里还一直在对已停掉的旧服务执行ping()方法。请帮忙看看是哪里的问题，谢谢了！

**Comment by 2881099** [comment]
如下图，在调用 ResetValue，这里会重新创建连接

![image](https://user-images.githubusercontent.com/16286519/68451220-da249780-0228-11ea-9ec1-f2ee7ba7bb96.png)

**Comment by 2881099** [comment]
哦哦，此时 ResetValue 得到的节点仍然是旧的

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/68452144-80be6780-022c-11ea-93f4-2d4a4c73b0bf.png)

测试OK，待会发个 3.1.14 版本

**Comment by quickappdev** [comment]
好的，谢谢了！效率真高！
