### ISSUE TITLE
使用sentinel出错

### ISSUE THREAD

**Issue by victor596** [2881099/csredis#209]
大牛，看看以下是哪里没设置正确。
![sentinel_error](https://user-images.githubusercontent.com/4110405/68728246-b767f980-0601-11ea-8273-2108d50b0f0e.jpg)

测试代码
 var csredis = new CSRedis.CSRedisClient(
            "mymaster",
            new[] { "127.0.0.1:26379", "127.0.0.1:26380" });
            foreach (int i in Enumerable.Range(1, 100))
            {
                csredis.Set($"key_{i}", i.ToString());
            }

sentinel配置如下:
redis-7010.conf
port 7010
maxmemory 100mb
appendonly no
dir "./Temp"
dbfilename "sentinel-target-7010.rdb"
save ""

redis-7011.conf
port 7011
maxmemory 100mb
appendonly no
slaveof 127.0.0.1 7010
rename-command CONFIG ""
rename-command SETEX ""
dir ".\Temp"
dbfilename "sentinel-target-7011.rdb"

sentinel-26379.conf
port 26379
protected-mode no
sentinel myid e06a11310ec072c682f3f045bad7cfcbd119816b
sentinel monitor mymaster 127.0.0.1 7010 1
sentinel down-after-milliseconds mymaster 1000
sentinel failover-timeout mymaster 2000
dir ".\Temp"
# Generated by CONFIG REWRITE
sentinel config-epoch mymaster 10
sentinel leader-epoch mymaster 14
sentinel known-slave mymaster 127.0.0.1 7011
sentinel known-sentinel mymaster 127.0.0.1 0 a7f43db6dd6aa95f515a06e64b4bc2f28e8bbc58
sentinel known-sentinel mymaster 127.0.0.1 26380 67c78784276228e04d9932dd122e1ad2a7521175
sentinel current-epoch 15

sentinel-26380.conf
port 26380
protected-mode no
sentinel myid 67c78784276228e04d9932dd122e1ad2a7521175
sentinel monitor mymaster 127.0.0.1 7010 1
sentinel down-after-milliseconds mymaster 1000
sentinel failover-timeout mymaster 2000
dir ".\Temp"
# Generated by CONFIG REWRITE
sentinel config-epoch mymaster 10
sentinel leader-epoch mymaster 15
sentinel known-slave mymaster 127.0.0.1 7011
sentinel known-sentinel mymaster 127.0.0.1 0 c47c18afd614db8bb1cc5cd6588aaea6a7ab18a8
sentinel known-sentinel mymaster 127.0.0.1 26379 e06a11310ec072c682f3f045bad7cfcbd119816b
sentinel current-epoch 15

**Comment by 2881099** [comment]
只有两哨兵？

哨兵最低配置：1主2从3哨兵

哨兵要选举投标，2个哨兵投标会 50%，作不了选举

**Comment by victor596** [comment]
哦，我是用 stackexchange.redis的环境来测的。 我再试试，  谢谢

**Comment by victor596** [comment]
改成1主2从3哨兵还是一样的问题。截图的最上面，我的测试环境根本就没有6379的端口，而这里会显示127.0.0.1：6379/0

**Comment by victor596** [comment]
大牛，我把master的listenning port 改成 6379就行了，是不是一个bug呀？

**Comment by 2881099** [comment]
用 redis-cli 连接任何一个哨兵，执行命令：

> SENTINEL get-master-addr-by-name mymaster

截图发来看下，6379，应该是这个返回的

**Comment by victor596** [comment]
图片上传不了，结果显示：
1） 127.0.0.1
2)  "7010"

**Comment by victor596** [comment]
> 图片上传不了，结果显示：
> 1） 127.0.0.1
> 2) "7010"

我把master改成 6379之后就测试成功，改回7010就失败

**Comment by 2881099** [comment]
改哪里 var csredis = new CSRedis.CSRedisClient(
"mymaster",
new[] { "127.0.0.1:26379", "127.0.0.1:26380" });

**Comment by victor596** [comment]
> 改哪里 var csredis = new CSRedis.CSRedisClient(
> "mymaster",
> new[] { "127.0.0.1:26379", "127.0.0.1:26380" });

master的监听端口改成6379,原来是7010

**Comment by victor596** [comment]
大牛，跟踪发 现：
     var pool = new RedisClientPool(connStr, client => { });
                var nodeKey = SentinelMasterName ?? pool.Key;
                if (Nodes.ContainsKey(nodeKey)) throw new Exception($"Node: {nodeKey} 重复，请检查");
                if (this.TryAddNode(nodeKey, pool) == false)
                {
                    pool.Dispose();
                    pool = null;
                    throw new Exception($"Node: {nodeKey} 无法添加");
                }
                if (firstPool == null) firstPool = pool;
本来是 7010的端口，后来 pool.key变成了6379

**Comment by 2881099** [comment]
nodeKey ??

> 大牛，跟踪发 现：
> var pool = new RedisClientPool(connStr, client => { });
> var nodeKey = SentinelMasterName ?? pool.Key;
> if (Nodes.ContainsKey(nodeKey)) throw new Exception($"Node: {nodeKey} 重复，请检查");
> if (this.TryAddNode(nodeKey, pool) == false)
> {
> pool.Dispose();
> pool = null;
> throw new Exception($"Node: {nodeKey} 无法添加");
> }
> if (firstPool == null) firstPool = pool;
> 本来是 7010的端口，后来 pool.key变成了6379

**Comment by victor596** [comment]
> nodeKey ??
> 
> > 大牛，跟踪发 现：
> > var pool = new RedisClientPool(connStr, client => { });
> > var nodeKey = SentinelMasterName ?? pool.Key;
> > if (Nodes.ContainsKey(nodeKey)) throw new Exception($"Node: {nodeKey} 重复，请检查");
> > if (this.TryAddNode(nodeKey, pool) == false)
> > {
> > pool.Dispose();
> > pool = null;
> > throw new Exception($"Node: {nodeKey} 无法添加");
> > }
> > if (firstPool == null) firstPool = pool;
> > 本来是 7010的端口，后来 pool.key变成了6379

RedisClientPoolPolicy.SetHost 这个方法发现会使用默认的端口6379

**Comment by victor596** [comment]
> > nodeKey ??
> > > 大牛，跟踪发 现：
> > > var pool = new RedisClientPool(connStr, client => { });
> > > var nodeKey = SentinelMasterName ?? pool.Key;
> > > if (Nodes.ContainsKey(nodeKey)) throw new Exception($"Node: {nodeKey} 重复，请检查");
> > > if (this.TryAddNode(nodeKey, pool) == false)
> > > {
> > > pool.Dispose();
> > > pool = null;
> > > throw new Exception($"Node: {nodeKey} 无法添加");
> > > }
> > > if (firstPool == null) firstPool = pool;
> > > 本来是 7010的端口，后来 pool.key变成了6379
> 
> RedisClientPoolPolicy.SetHost 这个方法发现会使用默认的端口6379

internal void SetHost(string host)  host参数会传入 mymaster

**Comment by 2881099** [comment]
SetHost(string host) 为传入 master 真实 ip 节点。
你的哨兵配置不正确吧。

检查：

1、用 redis-cli 连接任何一个哨兵，执行命令：
> SENTINEL get-master-addr-by-name mymaster

2、用 redis-cli 连接第1步返回的节点，执行命令：
> role
返回结果是什么？

**Comment by victor596** [comment]
我的类初始化是这样 
var csredis = new CSRedis.CSRedisClient( "mymaster",
new[] { "127.0.0.1:26379", "127.0.0.1:26380" });
然后跟踪是这样
![QQ截图20191114135832](https://user-images.githubusercontent.com/4110405/68830581-02a80800-06e7-11ea-9053-ffc5ca9ebaf3.jpg)
SetHost("mymaster") sethost不是应该是一个host吗？这里传入了 mymaster，所以程序就使用默认值127.0.0.1:6379 
我相同的配置用 servicestack.redis来测试是没问题的

**Comment by 2881099** [comment]
检查：

1、用 redis-cli 连接任何一个哨兵，执行命令：
> SENTINEL get-master-addr-by-name mymaster
2、用 redis-cli 连接第1步返回的节点，执行命令：
> role


返回结果是什么？反馈一下

**Comment by victor596** [comment]
> 检查：
> 
> 1、用 redis-cli 连接任何一个哨兵，执行命令：
> 
> > SENTINEL get-master-addr-by-name mymaster
> 
> 2、用 redis-cli 连接第1步返回的节点，执行命令：
> 
> > role
> 
> 返回结果是什么？反馈一下
第一条返回：
 1) "127.0.0.1"
 2) "7010"
第二条返回
 1) "sentinel"
 2) 1) "mymaster"

**Comment by 2881099** [comment]
所以不对，第二个角色不对，redis-server用的什么版本

**Comment by victor596** [comment]
在windows上的版本 Redis-x64-3.2.100

**Comment by 2881099** [comment]
https://github.com/2881099/csredis/blob/master/src/RedisSentinelManager.cs 164行

返回master才对

**Comment by 2881099** [comment]
https://github.com/2881099/csredis/blob/master/src/RedisSentinelManager.cs 164行

返回master才对

**Comment by 2881099** [comment]
role 返回 mymaster 不对啊，是不是配置错了。

前面说了最少3哨兵，你配了几个

**Comment by victor596** [comment]
> role 返回 mymaster 不对啊，是不是配置错了。
> 
> 前面说了最少3哨兵，你配了几个

3个哨兵

**Comment by 2881099** [comment]
第2部影片步，是在第一步返回的节点连接啊

resis-cli -p 7010
执行 role

结果是什么，我看你发的是在哨兵上执行的

**Comment by victor596** [comment]
> 第2步，是在第一步返回的节点连接啊
> 
> resis-cli -p 7010
> 执行 role
> 
> 结果是什么，我看你发的是在哨兵上执行的

返回 "master"
-----------------
我在linux上运行 redis-5.0.6之后，运行这两条命令跟windows上的版本一样
![QQ截图20191114135832](https://user-images.githubusercontent.com/4110405/68836891-53732d00-06f6-11ea-8486-431748b72ba1.jpg)

**Comment by 2881099** [comment]
> redis-cli -p 7010

> role

不是连哨兵，你链接的是哨兵执行的 role

**Comment by victor596** [comment]
> > redis-cli -p 7010
> 
> > role
> 
> 不是连哨兵，你链接的是哨兵执行的 role
![QQ截图20191114135832](https://user-images.githubusercontent.com/4110405/68837812-5838e080-06f8-11ea-9faf-5cfa83c1253d.jpg)

**Comment by 2881099** [comment]
好的，晚点排查下，现在在外面。

**Comment by 2881099** [comment]
https://github.com/2881099/csredis/blob/master/src/RedisSentinelManager.cs 164行
引入源码了吗，断点这里看看值

**Comment by victor596** [comment]
![QQ截图20191114135832](https://user-images.githubusercontent.com/4110405/68839820-70126380-06fc-11ea-9c42-e0d99ac9ff8c.jpg)

**Comment by 2881099** [comment]
继续向下，打印 master.Item1 + ':' + master.Item2;

**Comment by 2881099** [comment]
这个值是即将连接的 redis-server，它是 master 主节点。

**Comment by victor596** [comment]
![QQ截图20191114135832](https://user-images.githubusercontent.com/4110405/68840036-ddbe8f80-06fc-11ea-9dbe-a18fa631f9ad.jpg)

**Comment by 2881099** [comment]
所以不是 6379 啊

**Comment by victor596** [comment]
![QQ截图20191114135832](https://user-images.githubusercontent.com/4110405/68841430-8ff75680-06ff-11ea-96b3-976787457258.jpg)

所以我认为有一个bug,看上面有关sethost的描述：传入 sethost方法的是 "mymaster"并不是一个host,在这种情况下 sethost方法就默认使用 127.0.0.1:6379

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/68859888-3f91f000-0723-11ea-8449-f047cedfd425.png)

是这里的时候传进了 mymaster 吗？

string.IsNullOrEmpty(SentinelMasterValue) 这个条件不成立，值为 mymaster ？

但是上面的逻辑设置过值，看下图：

![image](https://user-images.githubusercontent.com/16286519/68859999-8b449980-0723-11ea-8ea6-22e91af5015a.png)

SentinelManager.Connect(SentinelMasterName, tmppoolPolicy._connectTimeout) 正是上面你断点调试返回的 127.0.0.1:7071

**Comment by victor596** [comment]
SentinelMasterName 是127.0.0.1 connStr是 mymaster

**Comment by victor596** [comment]
SentinelMasterName 是127.0.0.1:7010 , connStr是 mymaster

**Comment by victor596** [comment]
![QQ截图20191114135832](https://user-images.githubusercontent.com/4110405/68913462-53c30500-0796-11ea-8cec-37b6ae0c3d78.jpg)

**Comment by 2881099** [comment]
抱歉，我错了，前两天忙没空测试，刚才测试确实有这个bug，那个拼接字符串有问题。

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/68914101-71916980-0798-11ea-9aad-0e8cd4c7f3d1.png)

测试OK了，待会发个版本

**Comment by 2881099** [comment]
git commit 忘了给 #209 连接了，代码提交变化：https://github.com/2881099/csredis/commit/ea8cc9f2e33a3eb8bef01ab514382f9eb6e33991

**Comment by victor596** [comment]
好的，大牛
