### ISSUE TITLE
CSRedisClient 中关于 无序集合set的操作

### ISSUE THREAD

**Issue by markjoin123** [2881099/csredis#21]
什么时候可以添加

**Comment by 2881099** [comment]
我抽空加上，谢谢反馈

**Comment by 2881099** [comment]
无序集合、有序集合都有求并集、交集等相关功能
单节点模式下不会有问题
集群多节点模式下，存在冲突：原因是多个 key 可能不在一个redis-server，因此会抛出异常；若参数 keys 在同一节点，则不会报错。

请注意！

**Comment by 2881099** [comment]
因原作者未提供 SScan 的异步方法，所以 CSRedisClient/RedisHelper 都不支持 SScanAsync
