### ISSUE TITLE
Unexpected end of stream; expected type 'Int'

### ISSUE THREAD

**Issue by IrvingLu** [2881099/csredis#211]
作者你好：
我只是用了些简单的读取和写入操作，测试用着没有问题。但是生产环境是一天左右不使用就是出现这个报错，不知道是不是需要设置些什么？

我的连接符：
192.168.1.222:6379,ssl=False,password=123456,poolsize=5,preheat=false,writeBuffer=20480

具体报错位置：
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.Exists(String key)
   at RedisHelper`1.Exists(String key)

**Comment by 2881099** [comment]
idleTimeout= 看首页说明，加这个

**Comment by IrvingLu** [comment]
加上了idleTimeout= 0，对吧。然后，服务器上报错  
redis 仍然不可用，下一次恢复检查时间：11/14/2019 14:32:09，错误：(ERR max number of clients reached)   超过了连接数。这个的话我们这边是主动断开连接的么？

**Comment by 2881099** [comment]
idleTimeout=20000

**Comment by IrvingLu** [comment]
这个能大致说下原因嘛？就是我这么设置时候就没问题了是么

**Comment by 2881099** [comment]
也可能是阻塞导致的，单线程。

网络环境问题比较复杂。

ERR max number of clients reached 这是连接数太多导致的。

**Comment by IrvingLu** [comment]
再请问一下 每次读取都算一个连接嘛？读取完成不会自动断开吗？

**Comment by 2881099** [comment]
里面有连接池，连接资源循环重复使用，不是必然是新连接。

**Comment by IrvingLu** [comment]
好的 多谢
