### ISSUE TITLE
可否支持一下.Net Core 3.0，去掉NewtonSoft的依赖？

### ISSUE THREAD

**Issue by KevinChoiCGY** [2881099/csredis#213]
如题。

**Comment by 2881099** [comment]
序列化吗？

使用 string 方法放弃序列化。

或者 设置 CSRedisClient 对象 Serialize 和 De serialize，可以改变序列化。

**Comment by KevinChoiCGY** [comment]
其实我是想项目彻底脱去NewtonSoft的依赖,完全改由System.Text.Json.以防有人很顺手的就把Newtonsoft给用了.

**Comment by 2881099** [comment]
那就改源码吧，目前不适合去掉

**Comment by KevinChoiCGY** [comment]
多谢您的回复.
