### ISSUE TITLE
访问a:b:c:d 这种key的时候，很慢

### ISSUE THREAD

**Issue by gwhzh21** [2881099/csredis#215]
今天用jmeter对某个页面压测只有一句话RedisClient.Get<List<iteminfo>>("a:b:c:d")，100/s的并发，只有12/min的吞吐量。但是访问类似于RedisClient.Get<List<iteminfo>>("a-b-c-d")速度很快，不能理解。

**Comment by 2881099** [comment]
RedisClient 这个是什么对象

直接用 Get 返回字符串，测试结果怎么样


poolsize 设置到200

**Comment by gwhzh21** [comment]
poolsize设置到了200，但是依然很慢。重点一个也慢。我怀疑是不是windows下面的redis有坑。
public class Rds01 : RedisHelper<Rds01> { }
下面是测试用的代码:
var datas = WJWXCore.Rds01.Get<List<ItemInfo>>($"{(Request["Id"] ?? "")}:{(Request["ItemNo"] ?? "")}:num:discunt");

**Comment by gwhzh21** [comment]
找到了原因页面上有输出。忘记关闭了。谢谢。
