### ISSUE TITLE
使用 BLPop 命令在 RedisArray.cs 中报错的解决办法。

### ISSUE THREAD

**Issue by OAngs** [2881099/csredis#22]
\CSRedis\Internal\Commands\RedisArray.cs
第 82 行，在：
`long count = reader.ReadInt(false);`
下面增加：
`if (count == -1) return default(T);`

使用 BLPop 命令 阻塞超时后 reader.ReadInt(false) 会返回 -1。

**Comment by 2881099** [comment]
感谢反馈！

追问一下，阻塞超时在什么场景下会产生？

ps: 这样包容错误的做法有违《unix编程艺术》12、补救原则：出现异常时，马上退出，并给出足够错误信息。

**Comment by OAngs** [comment]
> 感谢反馈！
> 
> 追问一下，阻塞超时在什么场景下会产生？
> 
> ps: 这样包容错误的做法有违《unix编程艺术》12、补救原则：出现异常时，马上退出，并给出足够错误信息。

BLPop 命令，与 ServiceStack.Redis 的 BlockingDequeueItemFromList 相同，在指定时间内一阻塞方式监视指定可以 Key 如果这个 Key 存在或在设定的时间内（TimeOut 参数）新增了这个 Key 则返回 Value, 如果超过指定的时间这个 Key 仍未被创建，则返回空。

这个超时不应该被 throw Excption 出给调用者捕捉。

`
            CSRedis.CSRedisClient redisClient = new CSRedis.CSRedisClient(Setting.Redis.Connection);
            var val = redisClient.BLPop(8, $"{request.SystemCode}:{request.HandlerId}");
            if (!string.IsNullOrWhiteSpace(val))
            {
                //处理任务
                return new Entity.Result() { Flag = true };
            }

            return new Entity.ResultInfo() { Flag = false, Code = Entity.Enum.ResultCode.TimeOut, Msg = "超时。" };
`

CSRedisClient 类中增加：
`public string BLPop(int timeOut, string key) => ExecuteScalar(key, (c, k) => c.BLPop(timeOut, k));`

**Comment by 2881099** [comment]
了解下，redis功能真强大，这块之前没了解过。支持！

原作者没有支持 BLPopAsync，不知道出于什么原因。暂时先只支持同步方法。

```csharp
/// <summary>
/// 它是 LPOP 命令的阻塞版本，当给定列表内没有任何元素可供弹出的时候，连接将被 BLPOP 命令阻塞，直到等待超时或发现可弹出元素为止。警告：群集模式下，若keys分散在多个节点时，将报错
/// </summary>
/// <param name="timeOut">超时(秒)</param>
/// <param name="keys">一个或多个列表，不含prefix前辍</param>
/// <returns></returns>
public string BLPop(int timeOut, params string[] keys) => ClusterNodesNotSupport(keys, null, (c, k) => c.BLPop(timeOut, k));
/// <summary>
/// 它是 RPOP 命令的阻塞版本，当给定列表内没有任何元素可供弹出的时候，连接将被 BRPOP 命令阻塞，直到等待超时或发现可弹出元素为止。警告：群集模式下，若keys分散在多个节点时，将报错
/// </summary>
/// <param name="timeOut">超时(秒)</param>
/// <param name="keys">一个或多个列表，不含prefix前辍</param>
/// <returns></returns>
public string BRPop(int timeOut, params string[] keys) => ClusterNodesNotSupport(keys, null, (c, k) => c.BRPop(timeOut, k));
```

**Comment by 2881099** [comment]
nuget 版本 2.6.1
