### ISSUE TITLE
请问怎么执行获取时间的代码呢？ Redis 里面的 Time

### ISSUE THREAD

**Issue by FallStar0** [2881099/csredis#221]
怎么样才能获取到 Redis 的当前时间呢？
cli里面是直接 time
或者 return redis.call('TIME')

但是如果直接用 RedisHelper.Eval ，第二个参数key必填，看了源码不填还不行。

请问需要怎么调用呢？

**Comment by 2881099** [comment]
Eval key 随便填一个，这个 key 主要为了解决集群问题。

这些服务器管理的命令，被归纳到 NodesServerManager 属性中了。

> RedisHelper.NodesServerManager.Time()

**Comment by FallStar0** [comment]
谢谢，刚刚看到 NodesServerManager 那个部分也发现了~

**Comment by 2881099** [comment]
对，这里面的方法比较危险，也不常用，就收纳起来了
