### ISSUE TITLE
RedisHelper.Exists(cacheKey) 报错

### ISSUE THREAD

**Issue by ganqiyin** [2881099/csredis#225]
![image](https://user-images.githubusercontent.com/6446901/71343021-7b796a00-2599-11ea-81db-7f32a875ad22.png)

我想在循环的时候，排除不存在的KEY，结果报错
 
 
![image](https://user-images.githubusercontent.com/6446901/71343541-1aeb2c80-259b-11ea-8971-7d5f31c20a3a.png)

**Comment by 2881099** [comment]
怎么关了，这种错误是协议错误。

执行 exists 命名，服务端返回的是不是 Int，而是 Status

正常应该会返回 Int。
