### ISSUE TITLE
SortedSetAdd方法score分值超过15位后精度失效

### ISSUE THREAD

**Issue by powerglover** [2881099/csredis#226]
score分值为1234567890123456，保存后在redis查到值为1234567890123450,最后一位精度丢失，麻烦看下具体原因

**Comment by 2881099** [comment]
![image](https://user-images.githubusercontent.com/16286519/71400494-f908ad00-2661-11ea-8151-e17af1bdbc6b.png)

这里的锅

**Comment by 2881099** [comment]
> arg
1234567890123456
> ((double)arg).ToString("#")
"1234567890123460"

**Comment by 2881099** [comment]
double dbl = 1234567890123456;

怎么得到 dbl 的字符串原始内容

dbl.ToString("#") 不行，得到的字符串是：1234567890123460

**Comment by 2881099** [comment]
刚才用 core 3.1 测试，没有丢，你使用的哪个 .net 平台

**Comment by powerglover** [comment]
不好意思 刚才不在   我项目用的是  framework 4,5

**Comment by 2881099** [comment]
测了 java 也没问题，这个真坑。难道要改类型？

**Comment by powerglover** [comment]
是啊 之前用的stackexchange.redis  score用的16位，已经有很多业务数据了，现在突然发现最后一位精度不对了 导致更新不了对应缓存数据

**Comment by powerglover** [comment]
是啊 之前用的stackexchange.redis  score用的16位，已经有很多业务数据了，现在突然发现最后一位精度不对了 导致更新不了对应缓存数据

**Comment by 2881099** [comment]
我这要是改类型，也会坑到很多人。有没有其他解决办法，只要 ToString 得到完整数字就行。

**Comment by 2881099** [comment]
现在的问题是 ToString 丢了精。。但实际是有值

**Comment by powerglover** [comment]
可以加个其他类型的方法吗   比如long类型

**Comment by 2881099** [comment]
方法太多了，我看着头大。。

**Comment by 2881099** [comment]
v3.3.0 更新，将 double 参数变为 decimal 影响的方法：

- IncrByFloat
- HIncrByFloat
- Sorted Sets 所有和 score 有关的方法
- Geo 类型和 经纬度 有关的方法

更新 3.3.0 后可能需要修改一下传入参数的类型，不影数据结果。

**Comment by powerglover** [comment]
非常感谢，测试后能正常读写数据了

**Comment by 2881099** [comment]
如果遇到大数字解析出错，请升级到 v3.5.5
