### ISSUE TITLE
使用RedisHelper.CacheShellAsync方法后，会无限等待，不返回

### ISSUE THREAD

**Issue by hongbai** [2881099/csredis#23]
代码如下：
var list = await RedisHelper.CacheShellAsync(_key_bank_list, 60 * 60 * 24 * 7, () => bankdal.Banks());
其中bankdal.Banks()是一个异步方法，使用的是Dapper的QueryAsync方法读取数据库。
使用Postman进行提交测试，单步跟踪，到CacheShellAsync之后，从数据库中读取完数据，就直接跳到Startup.cs中注入CSRedis位置：
```
 RedisHelper.Initialization(csredis,
              value => Newtonsoft.Json.JsonConvert.SerializeObject(value),
              deserialize: (data, type) => Newtonsoft.Json.JsonConvert.DeserializeObject(data, type));
```
再之后就看不到其他的执行，而Postman还在等待接口返回数据，一直处在“loading”状态；如果Redis中有数据的话，就不会有这问题。应该是异步写Redis出的问题，麻烦修复一下，谢谢。

**Comment by 2881099** [comment]
感谢反馈！

请问 Bankdal.Banks() 返回类型是什么？

极可能是数据问题，我这里不好重现。

可以下载源码到本地，将源码添加到同一解决方案，把nuget引用改成项目引用。单步调试找到原因，还请反馈以便改进，谢谢！

**Comment by hongbai** [comment]
Bankdal.Banks()返回的是一个List<T>，但是数据比较多，能有4k+；试了下换成CacheShell是正常的

**Comment by 2881099** [comment]
哦，这个问题设置 writeBuffer 可以解决

```ini
127.0.0.1:6379,password=,defaultDatabase=13,poolsize=10,ssl=false,writeBuffer=20480,prefix=anzhong
```

同步方法没有限制。
异步方法由于用到了 SocketEventArgs，内部会申请 1000 * writeBuffer 的内存缓冲区重复利用。

**Comment by hongbai** [comment]
writeBuffer 加大之后搞定，多谢。
