### ISSUE TITLE
状态不可用，等待后台检查程序恢复方可使用。Connect to server timeout

### ISSUE THREAD

**Issue by mushramb0** [2881099/csredis#230]
csredis的版本是3.3.0 链接的是阿里云redis标准版 通过内网访问 经常会报这个错误 请问可能是什么原因导致 我的配置是poolsize=500,idleTimeout=60000,preheat=50,tryit=1

**Comment by 2881099** [comment]
testcluster=false,preheat=5

加上这个两个配置试下，另外把他们提供的 域名地址，改为 ip。

这个域名地址 dns 解析超级慢

**Comment by mushramb0** [comment]
按需改配置
