### ISSUE TITLE
BUG:使用.Async版本方法，导致依赖于AsyncLocal的异步上下文丢失

### ISSUE THREAD

**Issue by agebullhu** [2881099/csredis#231]
首先感谢作者付出的辛苦劳动，祝新年快乐！

导致如下代码出错：
/// <summary>当前线程的调用上下文</summary>
    public static GlobalContext Current
    {
      get
      {
        if (GlobalContext._local == null)
          GlobalContext._local = new AsyncLocal<GlobalContext>();
        else if (GlobalContext._local.Value != null && !GlobalContext._local.Value.IsDisposed)
          return GlobalContext._local.Value;
        GlobalContext._local.Value = IocHelper.Create<GlobalContext>();
        if (GlobalContext._local.Value != null)
          return GlobalContext._local.Value;
        IocHelper.AddScoped<GlobalContext, GlobalContext>();
        GlobalContext._local.Value = IocHelper.Create<GlobalContext>();
        return GlobalContext._local.Value;
      }
    }
在await后，new AsyncLocal<GlobalContext>().Value值被重置。

**Comment by 2881099** [comment]
内部有使用 TaskCompletionSource，不知道有没有影响

**Comment by 2881099** [comment]
有没有在小范围环境下测试，整理个简单的无其他依赖的代码 demo 发一份给我

**Comment by agebullhu** [comment]
有可能是我的代码的错误异常触发了这个问题，正在验证，后续结果会再报告给您

**Comment by agebullhu** [comment]
我的代码错误的将AsyncLocal定义成了ThreadStatic，导致线程切换时数据丢失，而您的代码正好引发了这个条件，说回来还得感谢你，否则这会是一个很严重的BUG，谢谢你！
