### ISSUE TITLE
怎么实现多端非争抢的模糊订阅

### ISSUE THREAD

**Issue by xiangxiren** [2881099/csredis#236]
问题如上

**Comment by 2881099** [comment]
只有 PSubscrible 方法

**Comment by 2881099** [comment]
使用方法和 Subscrible 类似

**Comment by xiangxiren** [comment]
但是PSubscribe方法，在我实际测试中有两个客户端（实际可能更多），只有一个客户端接收到了消息并且处理了，另一个没有接收到。我看PSubscribe方法注释上也说的“同条消息只处理一次”。

**Comment by 2881099** [comment]
那就没办法了，换个解决办法
