### ISSUE TITLE
3.3版本目前不支持链接字符串多IP配置吗

### ISSUE THREAD

**Issue by powerglover** [2881099/csredis#237]
原3.0版本链接字符串可以配置多个Redis IP,比如  connectionString="ip1:6379,ip2:6379,password=123456" 

3,3版本不支持，运行的时候会报错，只能配置单个IP

**Comment by 2881099** [comment]
这个是集群吧？只需要配置一个节点就行，其他节点在运行时自动构建

**Comment by powerglover** [comment]
不是集群，这2台都是一个WEB服务器，做了端口映射指向同一个阿里云Redis，之前这样部署是避免其中一台服务器出问题，可以自动切换到另外一台WEB服务器访问Redis。之前3.0的版本是支持这样配置，现在不行了只能设置1个地址了

**Comment by 2881099** [comment]
这种之前也不行，最多是配置解析没报错。

高可用方案，可以看看哨兵模式

**Comment by powerglover** [comment]
了解了，应该是记错了，  谢谢！
