### ISSUE TITLE
CsRedis:从始至终偶尔/经常性都报异常,异常原因,初步判断是流程问题, 测试String 字符串插入

### ISSUE THREAD

**Issue by AtlantisDe** [2881099/csredis#241]
## CsRedis:从始至终都报异常,异常原因,初步判断是流程问题,
-  已经被销毁的对象,被程序某处调用引发内部异常.

```c#
得出结论: 

Newlife.Redis 与 CsRedis:从始至终 均在初始阶段报异常.

Newlife.Redis : 
我看了是一个dynamic 一个属性问题.问题不大.
后面运行均稳定不报错的执行任务!

CsRedis:从始至终都报异常,异常原因,初步判断是流程问题,
已经被销毁的对象,被程序某处调用引发内部异常.

我均不知道这样是否影响正常无大碍使用,但是看到异常,就很强迫症.修下.
这个issue我会开个看是否是确实存在我所测的情况.然后修复下.  

```
![avatar](https://cdn.layui.com/upload/2020_1/3712296_1578871793102_33961.png)

![avatar](https://cdn.layui.com/upload/2020_1/3712296_1578871803823_56700.png)

## Demo代码 

- CsRedis 代码
```c#
            var csredis = new CSRedis.CSRedisClient("127.0.0.1:6379,password=,defaultDatabase=3,prefix=app_");

            RedisHelper.Initialization(csredis);

            Parallel.For(0, 50000000, new ParallelOptions() { MaxDegreeOfParallelism = 100 }, (i, loopState) =>
            {
                try
                {
                    RedisHelper.Set(GuidExtenions.N, "1111999", 180);
                }
                catch (Exception)
                {
                   //这里很容易爆各种异常,这个异常原因没搞明白 我坚持写完5000万 key先看会产生什么.暂时把异常处理掉.
                }
            });

```

- Newlife.Redis 代码
```c#
            var rds = new NewLife.Caching.FullRedis("127.0.0.1:6379", "", 1)
            { 
            };

            Parallel.For(0, 50000000, new ParallelOptions() { MaxDegreeOfParallelism = 100 }, (i, loopState) =>
            {
                try
                {
                    rds.Set(GuidExtenions.N, "1111999", 180);
                }
                catch (Exception)
                {

                    //这里很容易爆各种异常,这个异常原因没搞明白 我坚持写完5000万 key先看会产生什么.暂时把异常处理掉.
                } 
            });

```

**Comment by 2881099** [comment]
异常的原因大概是，并行任务还没执行完成，主进程退出了

**Comment by 2881099** [comment]
再补充下，不要在vs调试模式做这类测试，调试模式很慢

**Comment by AtlantisDe** [comment]
> 异常的原因大概是，并行任务还没执行完成，主进程退出了

主进程应该不会吧? 我调试进程都没结束过呢按理我主进程是一个单线程啊.单线程里的并发...
我没想明白 ! 好的... 看到你第二条回复了 ..但是调试 模式出现异常不应该能反应出啥问题么 ?

**Comment by 2881099** [comment]
AppDomain.CurrentDomain.ProcessExit += (s1, e1) =>
            {
                running = false;
            };
            try
            {
                Console.CancelKeyPress += (s1, e1) =>
                {
                    if (e1.Cancel) return;
                    running = false;
                };
            }
            catch { }

这两个事件，你看看会触发哪个。任何一个触发都会导致已释放的错误

**Comment by AtlantisDe** [comment]
> ```
>         AppDomain.CurrentDomain.ProcessExit += (s1, e1) =>
>         {
>             running = false;
>         };
>         try
>         {
>             Console.CancelKeyPress += (s1, e1) =>
>             {
>                 if (e1.Cancel) return;
>                 running = false;
>             };
>         }
>         catch { }
> ```
> 
> 这两个事件，你看看会触发哪个。任何一个触发都会导致已释放的错误

我现在是同样场景下, NewLife.Redis 却不会引发异常. 我们这边这个CSredis却出一样 你这个 代码我还不明白

**Comment by AtlantisDe** [comment]
var csredis = new CSRedis.CSRedisClient("127.0.0.1:6379,password=,defaultDatabase=3,prefix=app_,testcluster=false");
