### ISSUE TITLE
订阅的会不会引起异步程序整个阻塞？

### ISSUE THREAD

**Issue by scymen** [2881099/csredis#248]
先说一个之前遇到的问题：
.NET Generic Host 里使用多个 backgroundService ，并在其  ExecuteAsync 方法里使用阻塞 RedisHelper.BRpop .....  发现会阻塞其他 service 的执行甚至整个程序。后来修改为轮询 RedisHelper.Rpop... 没有内容时，再 Task.Delay(100) 。

如果我在 backgroundService 的  ExecuteAsync 方法里使用 RedisHelper.Subscribe... 会不会阻塞其他的任务？这里的 RedisHelper.Subscribe ，其内部实现，是单独开新线程来从Redis获取内容和阻塞？还是Task去处理？

不知道我没有表达清楚？请不吝赐教谢谢。

**Comment by 2881099** [comment]
> .NET Generic Host 里使用多个 backgroundService ，并在其 ExecuteAsync 方法里使用阻塞 RedisHelper.BRpop ..... 发现会阻塞其他 service 的执行甚至整个程序。后来修改为轮询 RedisHelper.Rpop... 没有内容时，再 Task.Delay(100)

这种情况是因为Task线程池耗尽，都在使用中，brpop是阻塞操作task会一直占用。解决办法可以设大线程池大小，ThreadPool.Setxxx，但是如果brpop无节制使用，再大的线程池也不够。

RedisHelper.Subscribe 内部是独立线程，不是Task，所以不会阻塞。

**Comment by scymen** [comment]
明白，谢谢
