### ISSUE TITLE
IncrBy：ERR hash value is not an integer

### ISSUE THREAD

**Issue by xiajinhu-it** [2881099/csredis#254]
[RedisException: ERR hash value is not an integer]
   CSRedis.Internal.IO.RedisReader.ReadType() +164
   CSRedis.Internal.IO.RedisReader.ExpectType(RedisMessage expectedType) +78
   CSRedis.Internal.IO.RedisReader.ReadInt(Boolean checkType) +82
   CSRedis.Internal.Commands.RedisInt.Parse(RedisReader reader) +59
   CSRedis.Internal.RedisConnector.Call(RedisCommand`1 command) +287

[RedisException: ERR hash value is not an integer
Command: HINCRBY csredis 1 1]
   CSRedis.CSRedisClient.GetAndExecute(RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes) +1249
   CSRedis.CSRedisClient.ExecuteScalar(String key, Func`3 hander) +731
   CSRedis.CSRedisClient.HIncrBy(String key, String field, Int64 value) +185

**Comment by 2881099** [comment]
他提示你类型不是 integer

检查下内容是什么类型

> hget csredis 1

**Comment by xiajinhu-it** [comment]
//
        // 摘要:
        //     为哈希表 key 中的指定字段的整数值加上增量 increment
        //
        // 参数:
        //   key:
        //     不含prefix前辍
        //
        //   field:
        //     字段
        //
        //   value:
        //     增量值(默认=1)
        public long HIncrBy(string key, string field, long value = 1);

**Comment by 2881099** [comment]
如果 redis 对应的值不是数字，会报错吗？

**Comment by xiajinhu-it** [comment]
函数定义时的入参是long，我调用时也传入的long类型

**Comment by 2881099** [comment]
什么时候定义的，你用 HGet("csredis", "1") 看返回什么

**Comment by xiajinhu-it** [comment]
HSet时用的RedisValue rv = 0; 
如果直接用long rv = 0 去HSet是正常的

**Comment by xiajinhu-it** [comment]
RedisValue 是StackExchange里的一个数据类型定义

**Comment by xiajinhu-it** [comment]
RedisValue的定义如下：
public struct RedisValue : IEquatable<RedisValue>, IComparable<RedisValue>, IComparable, IConvertible
    {
        public static RedisValue Null { get; }
        public static RedisValue EmptyString { get; }
        public bool HasValue { get; }
        public bool IsNull { get; }
        public bool IsInteger { get; }
        public bool IsNullOrEmpty { get; }

        public int CompareTo(RedisValue other);
        public override bool Equals(object obj);
        public bool Equals(RedisValue other);
        public override int GetHashCode();
        public override string ToString();
        public bool TryParse(out double val);
        public bool TryParse(out int val);
        public bool TryParse(out long val);

        public static bool operator ==(RedisValue x, RedisValue y);
        public static bool operator !=(RedisValue x, RedisValue y);

        public static implicit operator RedisValue(bool? value);
        public static implicit operator RedisValue(int value);
        public static implicit operator RedisValue(int? value);
        public static implicit operator RedisValue(long value);
        public static implicit operator RedisValue(long? value);
        public static implicit operator RedisValue(double value);
        public static implicit operator RedisValue(double? value);
        public static implicit operator RedisValue(string value);
        public static implicit operator byte[](RedisValue value);
        public static implicit operator string(RedisValue value);
        public static implicit operator RedisValue(byte[] value);
        public static implicit operator RedisValue(bool value);
        public static explicit operator bool?(RedisValue value);
        public static explicit operator int?(RedisValue value);
        public static explicit operator long?(RedisValue value);
        public static explicit operator double?(RedisValue value);
        public static explicit operator double(RedisValue value);
        public static explicit operator long(RedisValue value);
        public static explicit operator int(RedisValue value);
        public static explicit operator bool(RedisValue value);
    }

**Comment by xiajinhu-it** [comment]
如果把HSet的value类型是Object也没有问题

**Comment by xiajinhu-it** [comment]
把RedisValue value.ToString()再存就可以，写法问题 关闭吧
