### ISSUE TITLE
有发现 CSRedisClient.Set 方法无法正确设置过期时间的问题

### ISSUE THREAD

**Issue by JeffreySu** [2881099/csredis#255]
接口中设置了过期秒数，但是redis服务中始终是-1（永不过期）

**Comment by JeffreySu** [comment]
因为涉及到 Senparc.CO2NET 和 Weixin 里面几个模块，目前正在确认中，也不排除是上层模块的问题，先记一下，有新的情况我会发送到这里。

**Comment by 2881099** [comment]
好的

**Comment by JeffreySu** [comment]
不是 CsRedis 的问题，应该是有人提交了错误的 issue 证据。打扰了！

**Comment by JeffreySu** [comment]
@2881099 不过这里面确实连带出来另外一个问题：CsRedis接收的过期时间是int的，当开发者把一个小数强制取整之后（比如他必须要求缓存0.5秒），传入的可能就是0了，而系统会和-1等效起来。如果能够提供double类型的过期时间可能更好，或者干脆是重写一个方法支持TimeSpan类型。目前我其他库里面只能通过`TimeSpan?`类型，手动处理一下再传入。

**Comment by 2881099** [comment]
> @2881099 不过这里面确实连带出来另外一个问题：CsRedis接收的过期时间是int的，当开发者把一个小数强制取整之后（比如他必须要求缓存0.5秒），传入的可能就是0了，而系统会和-1等效起来。如果能够提供double类型的过期时间可能更好，或者干脆是重写一个方法支持TimeSpan类型。目前我其他库里面只能通过`TimeSpan?`类型，手动处理一下再传入。

public bool Set(string key, object value, TimeSpan expire, RedisExistence? exists = null)

是的，有重载是 TimeSpan

**Comment by JeffreySu** [comment]
TimeSpan 可以精确到 double 的秒数吗？

**Comment by 2881099** [comment]
是的，TimeSpan 是毫秒
