### ISSUE TITLE
Redis5.0通过redis-cli --cluster create搭建的集群，为什么stackexchange.redis可以访问，csredis却报Connection was not opened

### ISSUE THREAD

**Issue by xyz0822** [2881099/csredis#259]
如title描述
用的docker搭建，7001-7006端口都是可以访问通的，stackexchange.redis随便一个端口均可以访问，csredis却抛 CSRedis.RedisClientException:“Connection was not opened”
csredis版本：3.4.5

**Comment by xyz0822** [comment]
var conn = ConnectionMultiplexer.Connect("192.168.124.32:7001");
            IDatabase redisdb = conn.GetDatabase();
            var re = redisdb.StringSet("a", "1");
            var data = redisdb.StringGet("a");
            var redis = new CSRedis.CSRedisClient("192.168.124.32:7003");
            **var result = redis.Set("a", 1);** //抛异常
            Console.WriteLine("Hello World!");

**Comment by 2881099** [comment]
错误信息，堆栈发一下

**Comment by xyz0822** [comment]
| 名称 | 值 | 类型
-- | -- | -- | --
◢ | $exception | {"Connection was not opened"} | CSRedis.RedisClientException
  | ▶ Data | {System.Collections.ListDictionaryInternal} | System.Collections.IDictionary {System.Collections.ListDictionaryInternal}
  | HResult | -2146233088 | int
  | HelpLink | null | string
  | ▶ InnerException | null | System.Exception
  | Message | "Connection was not opened" | string
  | Source | "CSRedisCore" | string
  | StackTrace | "   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)\r\n   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)\r\n   at CSRedis.CSRedisClient.Set(String key, Object value, Int32 expireSeconds, Nullable`1 exists)\r\n   at RedisConsoleApp.Program.Main(String[] args) in D:\\Source\\Repos\\RedisConsoleApp\\Program.cs:line 16" | string
  | ▶ TargetSite | {T GetAndExecute[T](CSRedis.RedisClientPool, System.Func`2[SafeObjectPool.Object`1[CSRedis.RedisClient],T], Int32, Int32)} | System.Reflection.MethodBase {System.Reflection.RuntimeMethodInfo}
  | ▶ Static members |   |  
  | ▶ Non-Public members |   |

**Comment by 2881099** [comment]
var redis = new CSRedis.CSRedisClient("192.168.124.32:7001,testcluster=false");

这样呢

**Comment by xyz0822** [comment]
是docker搭建导致的问题，重新做了单机集群，访问正常了，不用testcluster=false也可以，多谢啦

**Comment by 2881099** [comment]
是的，因为 ConnectionMultiplexer.Connect("192.168.124.32:7001"); 不是集群连接，他只是连接一个所以正常。

new CSRedis.CSRedisClient("192.168.124.32:7001"); 默认会尝试加载所有节点来连接，如果节点配置成了 docker 内网，外部就访问不了，然后出现上面的错误。
