### ISSUE TITLE
对象池已释放，无法访问

### ISSUE THREAD

**Issue by hjj28810** [2881099/csredis#264]
你好，我现在用csredis用于阿里云的生产环境，环境是.net core 3.0，最近两天频繁的报“对象池已释放，无法访问”这个错
![企业微信截图_15839793689123](https://user-images.githubusercontent.com/16185484/76480990-3d2e7100-644b-11ea-80a6-987a195874f6.png)
这是初始化的代码
![企业微信截图_15839792065788](https://user-images.githubusercontent.com/16185484/76480972-2c7dfb00-644b-11ea-84c6-d5bff42db2c6.png)
![企业微信截图_15839792217640](https://user-images.githubusercontent.com/16185484/76480985-3a338080-644b-11ea-8152-c5482edcbf75.png)
这是调用的地方
![企业微信截图_15839792845683](https://user-images.githubusercontent.com/16185484/76481002-48819c80-644b-11ea-86d5-78143f35dabe.png)

**Comment by 2881099** [comment]
这个错误产生的原因：

1、CSRedisClient 对象执行了 Dispose 方法

2、系统事件被执行了

```csharp
AppDomain.CurrentDomain.ProcessExit += (s1, e1) =>
            {
                running = false;
            };
            try
            {
                Console.CancelKeyPress += (s1, e1) =>
                {
                    if (e1.Cancel) return;
                    running = false;
                };
            }
            catch { }
```

**Comment by hjj28810** [comment]
CSRedisClient 对象执行了 Dispose 方法，有情况会自己执行dispose么
系统的事件，我监控下康康

**Comment by hjj28810** [comment]
CSRedisClient我单例给了redishelper静态对象，redishelper会调用CSRedisClient的dispose么

**Comment by 2881099** [comment]
> CSRedisClient我单例给了redishelper静态对象，redishelper会调用CSRedisClient的dispose么

不会，如果没有手工调用 Dispose，检查下那两个事件有没有被执行。

**Comment by hjj28810** [comment]
这两个事件被执行了，意味着我整个服务都down了吧？

**Comment by 2881099** [comment]
应该是

**Comment by 2881099** [comment]
看看是什么原因被执行的，因为程序遇到了意外错误？

**Comment by hjj28810** [comment]
但是我linux用了supervisor守护我这个服务，我看到报错的时候，服务还是在的

**Comment by hjj28810** [comment]
行，我先加下这个两个事件的监控康康，有问题再来问，谢谢了

**Comment by 2881099** [comment]
supervisor守护，程序意外退出会重新启动。不能保证程序不退出

**Comment by 2881099** [comment]
Console.CancelKeyPress  这个事件，可以阻止内部执行

AppDomain.CurrentDomain.ProcessExit 这个事件就没法阻止了

**Comment by hjj28810** [comment]
但supervisor重新启动后，应该就会好了，因为我看到报错，手动调用supervisor 的restart就好了，然后过一阵子又会报错，所以应该进程应该是在的

**Comment by hjj28810** [comment]
会和我，用了三个静态的helper但是其实连接的同一个库，不同的db有关么？

**Comment by 2881099** [comment]
没关系的，RedisHelper 都是静态类，代理各种  CSRedisClient 实例的方法

**Comment by ClementeGao** [comment]
@hjj28810 解决了吗？  我也遇到了同样的错误

**Comment by hjj28810** [comment]
> @hjj28810 解决了吗？ 我也遇到了同样的错误

没，不过最近突然没再报这个错了，报另一个超时的错了。。。
