### ISSUE TITLE
 SafeObjectPool.Get 获取超时（10秒）

### ISSUE THREAD

**Issue by hjj28810** [2881099/csredis#267]
报这个错，想问下poolsize给多少好，如何监控连接的

**Comment by 2881099** [comment]
连远程 redis-server 处理不过来会这样

**Comment by hjj28810** [comment]
我在测试环境打印了Redishelper.Nodes.First().Value.Statistics
"Pool: 5/5, Get wait: 0, GetAsync wait: 0" 分别是啥意思

**Comment by 2881099** [comment]
可用数量/总数量(已打开发连接对象), wait: 排队等待的数量

**Comment by hjj28810** [comment]
,poolsize=50,ssl=false,writeBuffer=10240 我连接字符串给了50，这里是5正常么，还有什么属性可以设置避免这个问题的

**Comment by 2881099** [comment]
50个是最大，5是只开了5个，如果程序启动的时候5个不够，可以加上预热参数 preheat=50

**Comment by hjj28810** [comment]
idleTimeout 需要设置么

**Comment by hjj28810** [comment]
```
var rdsAntiRA = new CSRedisClient(Configuration.GetConnectionString("AntiRAConnection"));
services.AddSingleton(rdsAntiRA);
RdsAntiRA.Initialization(rdsAntiRA);
```
我先addsingleton再初始化的helper，我看到你例子是先初始化，再addsingleton并且加了缓存，需要改成你这样么

**Comment by 2881099** [comment]
idleTimeout 如果服务端会主动断开不活跃的连接，就设置一下，默认是15秒

**Comment by hjj28810** [comment]
我昨天poolsize改成200了，preheat=50 然后还是报了SafeObjectPool.Get 获取超时 这个错

**Comment by hjj28810** [comment]
RedisHelper`1.HGetAll(String key)
是这个方法抛出来的

**Comment by hjj28810** [comment]
用HGetAllAsync能解决这个问题么

**Comment by hjj28810** [comment]
早上小几千人同时在线就崩了。。。

**Comment by 2881099** [comment]
你先看看这个 https://blog.csdn.net/zhongguomao/article/details/52095883

**Comment by hjj28810** [comment]
我现在把hgetall改成hget了，还是报超时。。。奇怪的是我用了两台阿里云做slb，第一台不报错，第二台服务器就会报这个错
`System.TimeoutException: SafeObjectPool.Get 获取超时（10秒）。
   at SafeObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   at CSRedis.CSRedisClient.HGet(String key, String field)
   at RedisHelper`1.HGet(String key, String field)
`

**Comment by hjj28810** [comment]
第二台，报错的时间点一个是早上9点半-10点，一个是下午2点-3点

**Comment by 2881099** [comment]
是连续报错？之后自动又好了？

**Comment by hjj28810** [comment]
下午2点到3点的一个小时里，报了大概，7,80次，服务还是好的，就是这7,80次的请求会超时

**Comment by hjj28810** [comment]
现在访问量下来了就没报错了，我把poolsize已经放到500，预热也设到100了

**Comment by 2881099** [comment]
会自动恢复，说明处理不过来
用了阿里云，代表网络消耗会偏大，尤其要注意不要用了外网ip访问它

**Comment by 2881099** [comment]
7,80次错误，有可能是瞬间的流量进来，导致 pool 扩容创建新的连接，处理不过来

**Comment by 2881099** [comment]
此时整个 csrediscore 处于阻塞状态，不知道明白意思没

**Comment by hjj28810** [comment]
> 会自动恢复，说明处理不过来
> 用了阿里云，代表网络消耗会偏大，尤其要注意不要用了外网ip访问它

啥叫不要用了外网ip访问，我现在服务是在阿里云的两台机器上做slb，redis也是阿里云的rds

**Comment by hjj28810** [comment]
> > 会自动恢复，说明处理不过来
> > 用了阿里云，代表网络消耗会偏大，尤其要注意不要用了外网ip访问它
> 
> 啥叫不要用了外网ip访问，我现在服务是在阿里云的两台机器上做slb，redis也是阿里云的rds

服务器与redis是内网的

**Comment by 2881099** [comment]
你认为的内网，有可能走的链路不是内网，最好测试一下，a->b 两台机器每秒能创建多少个 socket

**Comment by hjj28810** [comment]
> 7,80次错误，有可能是瞬间的流量进来，导致 pool 扩容创建新的连接，处理不过来

我已经把poolsize放到500了，问个问题，两台服务器的配置poolsize都是500，那总量就是1000咯？

**Comment by 2881099** [comment]
最大情况时，不一定会用这么多

**Comment by hjj28810** [comment]
这两天还是有这个情况，我把redis的方法都是改成async的试试

**Comment by hjj28810** [comment]
再问个问题，我一个方法里，对redis多次操作，会产生连接多次才处理不过来了，我这个报错的方法里有6,7次get，del，set，等操作

**Comment by Aaron1213** [comment]
最终解决了吗 poolsize是500？ 还有看到有safeobjectpool 不确定是已经集成进去了 还是需要引入

**Comment by hjj28810** [comment]
最后解决了，就是poolsize给的不够

**Comment by Aaron1213** [comment]
谢谢回复  poolsize500吗 但是这个池大小会影响cpu吧 或者这个有标准吗 需要根据访问量吗

**Comment by hjj28810** [comment]
> 谢谢回复 poolsize500吗 但是这个池大小会影响cpu吧 或者这个有标准吗 需要根据访问量吗

根据量来
