### ISSUE TITLE
现在流行的三主三从怎么配置？

### ISSUE THREAD

**Issue by zhan520g** [2881099/csredis#268]
help

**Comment by 2881099** [comment]
var csredis = new CSRedis.CSRedisClient("127.0.0.1:6379,password=123");

这样就行了，如果是阿里云腾讯云集群，加上 testcluster=false

**Comment by zhan520g** [comment]
没看懂呢，我现在是6个redis 节点， 不是云上的。 您只展示了一个连接方式

**Comment by zhan520g** [comment]
> var csredis = new CSRedis.CSRedisClient("127.0.0.1:6379,password=123");
> 
> 这样就行了，如果是阿里云腾讯云集群，加上 testcluster=false

没看懂呢，我现在是6个redis 节点， 不是云上的。 您只展示了一个连接方式

**Comment by zhan520g** [comment]
我看了java的jredis, 需要配置6个端口，类似这样

Set<HostAndPort> jedisClusterNodes = new HashSet<HostAndPort>();
//Jedis Cluster will attempt to discover cluster nodes automatically
jedisClusterNodes.add(new HostAndPort("ip地址", 6380));
jedisClusterNodes.add(new HostAndPort("ip地址", 6381));
jedisClusterNodes.add(new HostAndPort("ip地址", 6382));
jedisClusterNodes.add(new HostAndPort("ip地址", 6383));
jedisClusterNodes.add(new HostAndPort("ip地址", 6384));
jedisClusterNodes.add(new HostAndPort("ip地址", 6385));

**Comment by 2881099** [comment]
你就这样用，然后观察一下 RedisHelper.Nodes 这个对象，有自动发现其他节点信心的。

**Comment by zhan520g** [comment]
> 你就这样用，然后观察一下 RedisHelper.Nodes 这个对象，有自动发现其他节点信息的。

谢谢，我试试

**Comment by byron2018** [comment]
var csredis = new CSRedis.CSRedisClient("127.0.0.1:6379,password=123"); 这样写不行，如果这个6397的节点挂了，就会报错。到底要怎样配置呢？
