### ISSUE TITLE
版本：CSRedisCore2.6.4 使用RedisHelper.HashSet("abce", "AA")报错“Index was outside the bounds of the array.”问题

### ISSUE THREAD

**Issue by ly-hyaline** [2881099/csredis#27]
public static RedisStatus HMSet(string key, params object[] keyValues)
        {
            List<object> args = new List<object> { key };
            for (int i = 0; i < keyValues.Length; i += 2)
            {
                if (keyValues[i] != null && keyValues[i + 1] != null)
                    args.AddRange(new[] { keyValues[i], keyValues[i + 1] });
            }
            return new RedisStatus("HMSET", args.ToArray());
        }

**Comment by HyalineFish** [comment]
理解了，是我用法不对；keyValues为键值对，不应该出现奇数数量

**Comment by HyalineFish** [comment]
我应该如何调用 HSet方法呢，RedisHelper有好多方法调取不到

**Comment by 2881099** [comment]
感谢反馈。

RedisHelper 命名有一点点差别，HSet 对应 HashSet，哈希相关的是 Hash 开头命名的方法。

keyValues 奇数判断，我稍后加上异常说明。

**Comment by ly-hyaline** [comment]
好的。

看源码HashSet 好像地下最终执行的是HMSet，其实我这边最常用的是HSet、HSetNx（用来当分布式lock、约束等），不过HMSet跟HSet就是一个批量的区别。

可否在RedisHelper里新增一个带CSRedisExistence参数的HashSet方法呢，RedisCommands这里的好多看着都想直接用。

**Comment by 2881099** [comment]
可以有。

hset/hmset 两个合并了，我看看怎么兼容 hsetnx 吧
