### ISSUE TITLE
创建client对象后，操作次数多，就会报：Connection was not opened

### ISSUE THREAD

**Issue by ulyanovsk** [2881099/csredis#271]
csreids 错误【47.111.8.250:6379/0】：Connection was not opened    at CSRedis.CSRedisClient.GetAndExecuteAsync[T](RedisClientPool pool, Func`2 handerAsync, Int32 jump, Int32 errtimes)

**Comment by 2881099** [comment]
用的哪个版本，升到最新，或者连接串加上：
idleTimeout=10000

**Comment by ulyanovsk** [comment]
用3.5.1

**Comment by ulyanovsk** [comment]
设置的是idleTimeout=20，我再按您说的idleTimeout=10000试试

**Comment by 2881099** [comment]
服务器环境呢，阿里云集群？这些都要说清楚

**Comment by ulyanovsk** [comment]
服务器：阿里云ecs，单机centos7，docker跑的redis,

**Comment by 2881099** [comment]
既然用了 docker ，看看网络有没有映射正确

**Comment by ulyanovsk** [comment]
好的，如果能重现，我把步骤都写出来，多谢
