### ISSUE TITLE
内存泄漏？

### ISSUE THREAD

**Issue by yuefengkai** [2881099/csredis#281]
您好！
---
项目上生产后内存频繁升高，Dump分析是RedisClientPool占用内存最高,请问是RedisClientPool导致？
还是我这边需要向其他方向找原因呢？
## CsRedisCore3.0.48

![image](https://user-images.githubusercontent.com/2100585/77721573-419b8200-7026-11ea-97f5-25d55402cd61.png)
![image](https://user-images.githubusercontent.com/2100585/77721501-0b5e0280-7026-11ea-819e-7d0655605d80.png)
![image](https://user-images.githubusercontent.com/2100585/77721981-63e1cf80-7027-11ea-8dbc-0ff5c879eb51.png)
![image](https://user-images.githubusercontent.com/2100585/77722148-dce12700-7027-11ea-8c14-8e9cb0af5714.png)

**Comment by yuefengkai** [comment]
单例模式

**Comment by 2881099** [comment]
升级，3.0.48很久的版本了。升级了再看

**Comment by yuefengkai** [comment]
好的,我这边升级一下再看

**Comment by 2881099** [comment]
RedisClientPool 是连接池管理类，除了存储最大的连接对象。当请求量大的时候排队，此时也会导致内存增加。

排队机制

同步10秒锁等带，会超时

异步不会超市，TaskSourceComplete 等待

看看是哪种情况

**Comment by 2881099** [comment]
连接池用完之后，才会排队

**Comment by yuefengkai** [comment]
应该不是csredis导致的
