### ISSUE TITLE
如何实现 redis监听key值过期失效

### ISSUE THREAD

**Issue by SunCe123** [2881099/csredis#285]
请问如何实现 redis监听key值过期失效，我想实现订单定时关闭业务逻辑

**Comment by 2881099** [comment]
关键字：redis notification

去搜索

**Comment by SunCe123** [comment]
1，Redis 配置 文件  更改  notify-keyspace-events "Ex"

2，RedisHelper.Subscribe(("__keyevent@0__:expired", msg => Console.WriteLine(msg.Body)));
