### ISSUE TITLE
使用管道各种报错

### ISSUE THREAD

**Issue by gwhzh21** [2881099/csredis#289]
在.net framework 4.5.2使用 CSRedisCore 3.1.6.0
代码如下:
int count = 100_00;
 var startpipe = WJWXCore.Rds01.StartPipe();
            for (int i = 0; i <  count ; i++)
            {
startpipe.Set($"m_0{i}", i);
}
startpipe.EndPipe();
报错:
System.NotSupportedException: 如果基础流不可搜寻，则当读取缓冲区不为空时，将无法写入到 BufferedStream。确保此 BufferedStream 下的流可搜寻或避免对此 BufferedStream 执行隔行读取和写入操作。
将count改成100
成功.
将count改成1000
第一次成功。间隔一秒，再调，继续上面的报错
将count改成500
第一次成功。间隔一秒，再调。出现 队列为空的报错
【127.0.0.1:6379/0】恢复检查时间：2020/4/15 10:07:32
System.InvalidOperationException: 队列为空。
   在 System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
   在 System.Collections.Generic.Queue`1.Dequeue()
   在 CSRedis.CSRedisClientPipe`1.EndPipe()

我认为可能不是bug,是我使用错误吗？

**Comment by gwhzh21** [comment]
windows 下面的redis 4.0.14.

**Comment by 2881099** [comment]
升级到3.6.2

**Comment by gwhzh21** [comment]
升级解决。

**Comment by 2881099** [comment]
记得用 using 包着 StartPipe 使用，不然可能造成连接不释放

**Comment by gwhzh21** [comment]
好的。明白了。
