### ISSUE TITLE
.ExpireAt设置毫秒级过期，貌似不准确啊

### ISSUE THREAD

**Issue by imgd** [2881099/csredis#297]
**client.ExpireAt(key, DateTime.Now.AddMilliseconds(expireMilliSeconds));**
毫秒级的测试不是很准确。

另外能不能 **.SetNx** 多重载添加一个过期时间啊
var pl = client.StartPipe();
            var result = client.SetNx(key, value);
            if (result)
            {
                client.ExpireAt(key, DateTime.Now.AddMilliseconds(expireMilliSeconds));
                //client.Expire(key, TimeSpan.FromMilliseconds(expireMilliSeconds));
            }
            pl.EndPipe();

好麻烦的。

**Comment by 2881099** [comment]
StartPipe 不适合需要返回值作为判断的场景。

你可能看下使用 redis lua 来执行。

**Comment by imgd** [comment]
请教一下csredis支持lua脚本吗，或者是其他的库？

**Comment by imgd** [comment]
我就想实现setnx 设置一个过期时间m/ms 操作是事务的，
或者有没有等价的命令写法？

**Comment by 2881099** [comment]
RedisHelper.Eval(luascript);

**Comment by imgd** [comment]
> RedisHelper.Eval(luascript);

谢谢
