### ISSUE TITLE
是否可以设置在连接发生异常的时候，不让整个池都不可用

### ISSUE THREAD

**Issue by momo314** [2881099/csredis#299]
目前我们系统在高峰期经常会遇到

>【10.0.0.8:6379/0】状态不可用，等待后台检查程序恢复方可使用。Connect to server timeout

（连接redis使用的是azure的v-net提供的内网ip）

但是在这个错误发生之后，其实redis还是可以正常连接的，但是因为这个异常会把整个池设置为unavailable，这样就会导致在一段时间内，redis对整个程序都是不可用状态，于是就会导致大约5-10分钟的异常请求数飙升。

按理说会有一个线程定时检测redis是否恢复，不应该会等到几分钟那么长时间才会恢复的，但是不知道为什么一直无法恢复

所以想请大佬帮忙分析下原因。

目前连接字符串中的配置为(不知道池设置这么大会不会影响什么)：
> preheat=50,poolsize=1000,idleTimeout=20000,syncTimeout=5000,tryit=0

另外出问题的时候请求数都在 8k/min 以上，虽然不是必现，但概率挺高的

**Comment by 2881099** [comment]
有可能连接频率太快，被 azure 网络策略拒绝访问了一会。

tryit=3 失败重试的次数，看看能不能缓解。

你的程序更需要一个全局异常拦截，防止异常退出。

**Comment by momo314** [comment]
加上了tryit=3，经过两天的观察，上述情况依然存在，而且无法连接的异常的出现并不是在请求量突然增高时发生的，而是在高峰期后期出现的，再加上没有找到 azure vm 网络策略相关的文档，所以并不太确定是不是网络策略的问题，请问关于 azure vm 网络策略这块有什么文档吗，还是根据经验

![image](https://user-images.githubusercontent.com/2268060/83007422-3c6aab80-a046-11ea-95ca-d5f62d3ee13f.png)


> 有可能连接频率太快，被 azure 网络策略拒绝访问了一会。
> 
> tryit=3 失败重试的次数，看看能不能缓解。
> 
> 你的程序更需要一个全局异常拦截，防止异常退出。

**Comment by 2881099** [comment]
是根据经验判断的，Connect to server timeout 这个错误是 5 秒连不上 redis-server 才会出现。

连接串的默认值：connectTimeout=5000

**Comment by momo314** [comment]
最终修改了```net.core.somaxconn```和```net.ipv4.tcp_max_syn_backlog```目前看貌似不太会出现这个问题了。不过始终觉得发生连接异常时使整个池不可用不太合适

**Comment by 2881099** [comment]
> 最终修改了`net.core.somaxconn`和`net.ipv4.tcp_max_syn_backlog`目前看貌似不太会出现这个问题了。不过始终觉得发生连接异常时使整个池不可用不太合适

24天前的问题哦，这么久才解决的吗？如果不让整个池不可用，由得程序不断的 connect redis-server 会造成更大问题。

**Comment by LiYueH** [comment]
> 



> 最终修改了`net.core.somaxconn`和`net.ipv4.tcp_max_syn_backlog`目前看貌似不太会出现这个问题了。不过始终觉得发生连接异常时使整个池不可用不太合适

你好，可以请问下，net.core.somaxconn和net.ipv4.tcp_max_syn_backlog，在哪修改吗，我们用的也是
azure linux
