### ISSUE TITLE
修改缓存的时候怎么才能使过期时间不变化呢？

### ISSUE THREAD

**Issue by caopengfei** [2881099/csredis#3]
比如，我现在设置key=aaa,value=bbb，600秒后过期，但是在过了320秒后，我要修改这个数据，key=aaa,value=abc，但是过期时间不改变（现在应该是280）。这个该如何操作呢？set方法有个默认值，如果不传递的话，会导致过期时间变更为-1

**Comment by 2576168920** [comment]
现在有redis6.0之后有set key value keepttl命令，不知道CSRedisCore是否增加了keepttl
