### ISSUE TITLE
BLPop返回 Unable to read data from the transport connection

### ISSUE THREAD

**Issue by bbenph** [2881099/csredis#300]
抄的 https://www.cnblogs.com/kellynic/p/9952386.html
版本 3.6.3

代码 如下
//程序1：使用代码实现订阅端
while (running) {
	try {
		var msg = RedisHelper.BLPop(5, "list1");
		if (string.IsNullOrEmpty(msg) == false) {
			Console.WriteLine(msg);
		}
	} catch (Exception ex) {
		Console.WriteLine(ex.Message);
	}
}

//程序2：使用代码实现发布端
RedisHelper.LPush("list1", "111");

**Comment by bbenph** [comment]
报错详情:
csreids 错误【ip:6379/1】：Unable to read data from the transport connection: 由于连接方在一段时间后没有正确答复或连接的主机没有反应，连接尝试失败。.    at CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   at CSRedis.CSRedisClient.NodesNotSupport[T](String[] keys, T defaultValue, Func`3 callback)
   at CSRedis.CSRedisClient.BLPop(Int32 timeout, String[] keys)
   at RedisHelper`1.BLPop(Int32 timeout, String[] keys)

**Comment by 2881099** [comment]
syncTimeout 这个设置了吗，默认是10秒

10秒没读取到数据就会报上面的错误。

RedisHelper.BLPop(5     这里的等待时间必须小于 syncTimeout（注意单位不同）

**Comment by bbenph** [comment]
是我链接字符串的超时时间大于了 RedisHelper.BLPop(XXX)的时间
