### ISSUE TITLE
关于枚举类型序列化的问题

### ISSUE THREAD

**Issue by momo314** [2881099/csredis#312]
请问json序列化的时候要使用```StringEnumConverter```呢？
个人认为使用默认的序列化设置，将枚举类型序列化为数值类型更方便一些，而且如果后续更改枚举定义的话，也不会有什么影响。
使用字符串来序列化枚举类型是有什么更深层的考虑吗？

**Comment by 2881099** [comment]
CSRedisClient 有这个属性可以自定义 CurrentSerialize

**Comment by momo314** [comment]
嗯，我知道这里可以自定义，就是打算自定义的过程中提的这个issue，想问一下大佬这里有没有什么特殊的用意，怕有坑

**Comment by 2881099** [comment]
为了保证不受外部 JsonSettings 设置的影响，所以默认用的内部独立的 JaonSettings。

**Comment by momo314** [comment]
好的，收到
