### ISSUE TITLE
建议增加支持多个key的eval方法

### ISSUE THREAD

**Issue by xiangxiren** [2881099/csredis#319]
现在我有一个需求，需要传多个key和多个value，然后执行一段lua脚本

通过查看其它issue发现，只放开一个 key 是为了分区/集群定位

是否可以增加支持多个key的方法（明确标注不支持分区/集群）

**Comment by 2881099** [comment]
办法1：

在 lua 内写死其他的 key

办法2：

using (var rc = RedisHelper.Instance.Nodes.First().Value.Get())
{
rc.Value.Eval 
}

**Comment by xiangxiren** [comment]
> 办法1：
> 
> 在 lua 内写死其他的 key
> 
> 办法2：
> 
> using (var rc = RedisHelper.Instance.Nodes.First().Value.Get())
> {
> rc.Value.Eval
> }

key是动态的，有时只传一个，有时传多个。key和value的个数是对应的。
目前我就通过RedisHelper.Instance.Nodes.First().Value.Get()这样去拿的
