### ISSUE TITLE
内存异常 OutOfMemoryException

### ISSUE THREAD

**Issue by kj13755097782** [2881099/csredis#332]
2020-08-22 01:11:01.9647|ERROR|IBMS.Service.Host.Program.TaskSchedulerUnobservedTaskExceptionHandler| Task Scheduler Exception 
 System.AggregateException: 未通过等待任务或访问任务的 Exception 属性观察到任务的异常。因此，终结器线程重新引发了未观察到的异常。 ---> System.Exception: 【192.168.3.219:6379/0】状态不可用，等待后台检查程序恢复方可使用。引发类型为“System.OutOfMemoryException”的异常。 ---> System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 CSRedis.CSRedisClient.<GetAndExecuteAsync>d__328`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 CSRedis.CSRedisClient.<ExecuteScalarAsync>d__334`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   在 IBMS.Service.Core.Cache.RedisClients.CSRedisCache.<AddAllAsync>d__14`1.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
   在 CSRedis.Internal.ObjectPool.ObjectPool`1.getFree(Boolean checkAvailable)
   在 CSRedis.Internal.ObjectPool.ObjectPool`1.Get(Nullable`1 timeout)
   在 CSRedis.CSRedisClient.GetAndExecute[T](RedisClientPool pool, Func`2 handler, Int32 jump, Int32 errtimes)
   在 CSRedis.CSRedisClient.ExecuteNonQuery(String[] key, Func`3 hander)
   在 CSRedis.CSRedisClient.MSetInternal(RedisExistence exists, Object[] keyValues)
   在 CSRedis.CSRedisClient.MSet(Object[] keyValues)
   在 IBMS.Service.Core.Cache.RedisClients.CSRedisCache.<AddAllAsync>d__13`1.MoveNext()
   --- 内部异常堆栈跟踪的结尾 ---
---> (内部异常 #0) System.Exception: 【192.168.3.219:6379/0】状态不可用，等待后台检查程序恢复方可使用。引发类型为“System.OutOfMemoryException”的异常。 ---> System.OutOfMemoryException: 引发类型为“System.OutOfMemoryException”的异常。
   在 CSRedis.CSRedisClient.<GetAndExecuteAsync>d__328`1.MoveNext()
--- 引发异常的上一位置中堆栈跟踪的末尾 ---

服务器：winserver 2012 r2
总内存24G，异常时间内存占用（正常情况，内存占用都不高，10%不到）
.NET Framework 4.7.2
ssl=false,autoDispose=true,testcluster=false,asyncPipeline=true,tryit=0,preheat=5,poolsize=100,syncTimeout=10000,idleTimeout=14000,connectTimeout=5000
redis在本地运行，平均每秒写入6000条左右分8次，每秒查询KEY 60+，总数据量5万条，分3个主要库
[test.log](https://github.com/2881099/csredis/files/5123747/test.log)

**Comment by 2881099** [comment]
asyncPipeline=false

这样会出现问题吗？

**Comment by 2881099** [comment]
能否提供一个 console dome 重现该问题

**Comment by kj13755097782** [comment]
> asyncPipeline = false
> 
> 这样会出现问题吗？
没有试过，不过写入实际调用的是同步，这有影响吗

**Comment by ShangSRuoShui** [comment]
同步写入  配置是默认的
同样出现OutOfMemoryException
![image](https://user-images.githubusercontent.com/78338962/106420951-b6d1b200-6496-11eb-9889-9aaabbf87ba8.png)
![image](https://user-images.githubusercontent.com/78338962/106421032-e84a7d80-6496-11eb-9902-0b40f842c11f.png)

**Comment by 2881099** [comment]
试试 append 命令
