### ISSUE TITLE
关于lock的一点疑问

### ISSUE THREAD

**Issue by ccccccmd** [2881099/csredis#336]
https://github.com/2881099/csredis/blob/a5de3866e884e811182352defe23581c065338b5/src/CSRedisCore/CSRedisClient.cs#L4344-L4359

看了下实现，
Lock 函数 中 `timeoutSeconds` 既是获取锁这个过程的最长等待时间 ，又是锁的有效时间，感觉有点混乱。
有个场景
30s没有获取到锁，就跳出，提示繁忙稍后再试；
获取到锁后，执行到任务完毕自动释放，执行时间可能大于 30s；这样 `timeoutSeconds`就很难定义

**Comment by 2881099** [comment]
执行时间超时有 autoDelay 。

timeoutSeconds 主要是抢锁超时。

**Comment by ccccccmd** [comment]
谢谢，了解了
