### ISSUE TITLE
哨兵模式，当readOnly = false时，报错，为true正常

### ISSUE THREAD

**Issue by HonghuiHu** [2881099/csredis#337]
哨兵模式，当readOnly = false时，报错，为true正常，但是目前我的必须是false，因为从节点是只读的··，
![image](https://user-images.githubusercontent.com/39977344/92984547-74a2d680-f4dd-11ea-8451-3b8126655844.png)

**Comment by HonghuiHu** [comment]
错误信息：System.Exception:“Redis Sentinel Master is switching：Connection was not opened”   实际我用工具连主节点，一切是正常的

**Comment by HonghuiHu** [comment]
难道是因为主从集群的docker-compose.yml的节点  配置的是容器名而不是IP导致的？

**Comment by 2881099** [comment]
是有可能的，网络环境需要自己分析解决

**Comment by HonghuiHu** [comment]
已经解决了，的确是网络环境问题，通过Dockercompose.yml 直接指定主从节点IP+PORT，这样哨兵节点在查询master的时候，就不会返回容器IP，而是我指定的IP，这样外网程序就能正常访问了

**Comment by thicktao** [comment]
> 已经解决了，的确是网络环境问题，通过Dockercompose.yml 直接指定主从节点IP+PORT，这样哨兵节点在查询master的时候，就不会返回容器IP，而是我指定的IP，这样外网程序就能正常访问了

亲，可以发下一配置吗？

**Comment by thicktao** [comment]
@HonghuiHu 亲，可以发下一配置吗？
