### ISSUE TITLE
哨兵调用异常

### ISSUE THREAD

**Issue by mswinner** [2881099/csredis#341]
System.Exception:“Redis Sentinel Master is switching：Connection was not opened”

你好，我是在k8s 用helm部署的redis-ha 1主2从3哨兵

**Comment by mswinner** [comment]
> 网络通吗？检查一下

用redis cli 工具 在k8s 网络 及 用redis一些工具 外部网络 都是 通的   不管是 master 还是 sentinel 都可以连

**Comment by 2881099** [comment]
但是提示不通，你翻源码看看哨兵返回的 naster 信息是不是内网的。

sentinel get-master-addr-by-name mymaster

**Comment by mswinner** [comment]
用redis-ha 的哨兵地址 且必须是k8s的网络里才行
