### ISSUE TITLE
【建议】请问可以针对CacheShell方法再添加一个参数用于设置结果为null的缓存过期时间吗

### ISSUE THREAD

**Issue by xuejmnet** [2881099/csredis#344]
最近一直在用CacheShell，也用它实现了一个缓存的通用设计，但是针对雪花id如果缓存过期时间过短会导致缓存本身无法缓存太久，如果缓存过期时间过长会导致如果恶意请求猜中了我的那一次雪花id因为CacheShell的缓存穿透机制我就要等到对应设置的缓存过期时间才可以过期掉对应的缓存，所以能否添加一个额外参数来扩展CacheShell设置当hset的item1为null的时候可以单独设置缓存过期时间而不是都用一个值，谢谢

**Comment by xuejmnet** [comment]
如果是自增Id的情况下就更加不得了了别人直接请求不存在的数据会导致我真实存在的数据没办法被缓存命中,所以希望可以单独有个缓存为null的缓存过期时间来达到不存在的时候利用短时间就可以了

**Comment by 2881099** [comment]
起初是为了防止击穿，可以考虑把代码提出来改

csredis 目前机制确定了不好改，以免影响其他人。
