### ISSUE TITLE
IDistributedCache add list support

### ISSUE THREAD

**Issue by yedajiang44** [2881099/csredis#346]
`IDistributedCache` 和 `CSRedisCache` 能否添加对list的支持？？
实际业务上虽说可以用string或者byte[]去代替，但是大对象且并发下效率并不高，所以想问下能否支持该功能？

**Comment by 2881099** [comment]
redis 有多种数据类型，了解一下：http://redis.cn/

**Comment by yedajiang44** [comment]
> redis 有多种数据类型，了解一下：http://redis.cn/
感谢您的即时回复，可能是我表述问题

你说的这个我知道，但是`IDistributedCache`的接口并不支持`System.Collections.Generic.List`，这玩意如果元素多了之后无论用已支持的扩展

`IDistributedCache.Set(string key, byte[] value, DistributedCacheEntryOptions options)`

还是

`IDistributedCache.SetString(this IDistributedCache cache, string key, string value)`

它们在并发下都不理想

所以想问下能否添加`IDistributedCache`对`System.Collections.Generic.List`的支持，并使用redis的list去存储。

**Comment by 2881099** [comment]
这种情况建议直接用 redis client

**Comment by yedajiang44** [comment]
目前确实只能这样，但是如果支持的话那就更好了。
