### ISSUE TITLE
ceredis耗时问题求解

### ISSUE THREAD

**Issue by xiaohanlaila** [2881099/csredis#356]
大神你好，如下图所示，同一断点下的两次请求，第一次175ms，第二次（5s内）37ms，然后过段时间再执行，耗时又会变为180ms左右，请问这个client是重新连接了吗？如何保持长连接呢

![image](https://user-images.githubusercontent.com/38322997/103078856-b2031e00-460d-11eb-9394-0dfaba38222c.png)

**Comment by xiaohanlaila** [comment]
请问连接字符串中的 idleTimeout 这个的配置单位是毫秒吗

**Comment by 2881099** [comment]
以 readme 描述为准

**Comment by 2881099** [comment]
保持长连接没用，你在连接远程服务器吧，过一会就会被回收

**Comment by xiaohanlaila** [comment]
但是我感觉这个回收的频率很高啊，没超过一分钟的感觉

**Comment by 2881099** [comment]
看 IdleTimeout 设置的值

**Comment by xiaohanlaila** [comment]
好的，非常感谢，通过本地连接，是不是就可以解决这个问题？

**Comment by 2881099** [comment]
本地速度很快，没这个卡顿现象

**Comment by xiaohanlaila** [comment]
好的，我试试，非常感谢大神
