### ISSUE TITLE
最新的修改什么时候能发一个版本到nuget吗？

### ISSUE THREAD

**Issue by wsq003** [2881099/csredis#357]
包含分布式锁的bug修正，以及.net5的支持。

**Comment by 2881099** [comment]
分布式锁的 bug 是指哪部分？

.net5 默认是支持的吧。

**Comment by wsq003** [comment]
#350 主要是这个PR。没这个PR的话，分布式锁有点危险。

**Comment by 2881099** [comment]
Thread.Sleep和Task.Delay都可能会有比较大的误差。

您的意思用哪个精准一些，但是代码内分布式锁实现，没有使用这两个

**Comment by 2881099** [comment]
考虑到更改 API 会带来后续技术咨询成本，所以一直没有发布版本。

**Comment by wsq003** [comment]
我不确定Timer里面用的是哪个。。。。

**Comment by wsq003** [comment]
> 
> 
> 考虑到更改 API 会带来后续技术咨询成本，所以一直没有发布版本。

#350 之所以会提出来，是因为我们在项目里面确实因为pexpire的问题遇到bug了，分布式锁没有如预期的那样超时，于是线上出了故障。目前我们系统里面用的是自己修改的版本，这样不太方便。还是希望用nuget的版本，比较统一。

**Comment by 2881099** [comment]
v3.6.6 #350 #357

已上传

**Comment by wsq003** [comment]
> 
> 
> v3.6.6 #350 #357
> 
> 已上传

太棒了。谢谢！我们这边更新下测试下。
