### ISSUE TITLE
 CSRedis.RedisClientException: Connection was not opened

### ISSUE THREAD

**Issue by oreo1024** [2881099/csredis#388]
CSRedis.RedisClientException: Connection was not opened    at CSRedis.Internal.IO.RedisIO.GetOrThrow[T](T obj)    at CSRedis.Internal.IO.RedisIO.get_Stream()    at CSRedis.Internal.IO.RedisIO.WriteAsync(RedisCommand command)    at CSRedis.Internal.RedisConnector.CallAsync[T](RedisCommand`1 command)    at CSRedis.RedisClient.WriteAsync[T](RedisCommand`1 command)    at CSRedis.CSRedisClient.SetAsync(String key, Object value, TimeSpan expire, Nullable`1 exists)

**Comment by 2881099** [comment]
Connection was not opened
