### ISSUE TITLE
The background color of output/log on the console

### ISSUE THREAD

**Issue by Scythemen** [2881099/csredis#423]
- It seems that the background color of output on the console was configurated to GREEN, and then all the following logging on the console are green background. Why this? How can I turn this off?

- It output Chinese on the console when subscribing to a channel, could it be english?

Thanks.

**Comment by 2881099** [comment]
please use FreeRedis

**Comment by 2881099** [comment]
https://github.com/2881099/FreeRedis

**Comment by Scythemen** [comment]
Wow... Thanks. But what's the defference between csredis & FreeRedis?
