### ISSUE TITLE
请教一下，RedisHelper初始化方式变了么？现在已经深度集成Json.net为序列化插件么？

### ISSUE THREAD

**Issue by 2881099** [2881099/csredis#45]
请教一下，RedisHelper初始化方式变了么？现在已经深度集成Json.net为序列化插件么？
还有以前的自定义序列化接口么？

我们之前使用 Jil 序列化，保留上一个版本的初始化接口就更好了

**Comment by 2881099** [comment]
内部引用 newtownsoft.json 序列化/反序列了，需要修改下代码规则。

**Comment by 2881099** [comment]
序列化/反序列化，现在要放在 CSRedisClient 对象上配置，RedisHelper 静态类只是它的代理

```csharp
//自定义序列化/反序列化
var csredis = new CSRedisClient("127.0.0.1:6379");
csredis.Serialize = value => JsonConvert.SerializeObject(value);
csredis.Deserialize = (value, type) => JsonConvert.DeserializeObject(value, type);
RedisHelper.Initialization(csredis);
```

注意：普通的值类型不走序列化/反序列化，比如 RedisHelper.Get<Guid>("xxx")，其实是走 Guid.TryParse

默认序列化/反序列化仍然使用 NewtownSoft.json。

**Comment by hellozhang** [comment]
### 这种情况偶有发生，什么问题，


CSRedis.RedisException: ERR wrong number of arguments for 'set' command
   

在 CSRedis.Internal.IO.RedisReader.ReadType()
   在 CSRedis.Internal.Commands.RedisStatus.Nullable.Parse(RedisReader reader)
   在 CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   在 CSRedis.RedisClient.Write[T](RedisCommand`1 command)
   在 CSRedis.RedisClient.Set(String key, Object value, Nullable`1 expirationSeconds, Nullable`1 condition)
   在 CSRedis.CSRedisClient.<>c__DisplayClass15_0.<SetBytes>b__0(RedisClient c, String k)
   在 CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   在 CSRedis.CSRedisClient.SetBytes(String key, Byte[] value, Int32 expireSeconds, Nullable`1 exists)
   在 CSRedisHelper.SetBytes(String key, Byte[] value, Int32 expireSeconds, Nullable`1 exists)
   在 Xiannvhu.Project.Infrastructure.RedisHelper.Set(String key, Object value, DateTime expireTime) 位置 F:\土驴网\XVH\prjXianNvHu\Xiannvhu.ApiServer\Xiannvhu.Project.Infrastructure\Cache\RedisHelper.cs:行号 134
   在 Xiannvhu.ClientForAdmin.Controllers.HomeController.<Login>d__1.MoveNext() 位置 F:\土驴网\XVH\prjXianNvHu\Xiannvhu.Client\Xiannvhu.ClientForAdmin\Controllers\HomeController.cs:行号 56
--- 引发异常的上一位置中堆栈跟踪的末尾 ---
   在 System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   在 System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   在 lambda_method(Closure , Task )
   在 System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass34.<BeginInvokeAsynchronousActionMethod>b__33(IAsyncResult asyncResult)
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3c()
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass45.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3e()
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass45.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3e()
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass30.<BeginInvokeActionMethodWithFilters>b__2f(IAsyncResult asyncResult)
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass1e.<>c__DisplayClass28.<BeginInvokeAction>b__19()
   在 System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass1e.<BeginInvokeAction>b__1b(IAsyncResult asyncResult)

**Comment by hellozhang** [comment]
> **CSRedis.RedisException: ERR wrong number of arguments for 'set' command**
> **CSRedisHelper  就是基类的 RedisHelper ，为了防止跟系统原有的冲突**


   在 CSRedis.Internal.IO.RedisReader.ReadType()
   在 CSRedis.Internal.Commands.RedisStatus.Nullable.Parse(RedisReader reader)
   在 CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command)
   在 CSRedis.RedisClient.Write[T](RedisCommand`1 command)
   在 CSRedis.RedisClient.Set(String key, Object value, Nullable`1 expirationSeconds, Nullable`1 condition)
   在 CSRedis.CSRedisClient.<>c__DisplayClass15_0.<SetBytes>b__0(RedisClient c, String k)
   在 CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander)
   在 CSRedis.CSRedisClient.SetBytes(String key, Byte[] value, Int32 expireSeconds, Nullable`1 exists)
   在 CSRedisHelper.SetBytes(String key, Byte[] value, Int32 expireSeconds, Nullable`1 exists)
   在 RedisHelper.Set(String key, Object value, DateTime expireTime) 位置 

   public static void Set(string key, object value, DateTime expireTime)
        {

            TimeSpan span = DateTime.Now.AddMinutes(30) - DateTime.Now;//默认为30分钟
            if (expireTime > DateTime.Now)
            {
                span = expireTime - DateTime.Now;
            }
            TimeSpan sec = TimeSpan.Parse(span.Days + "." + span.Hours + ":" + span.Minutes + ":" + span.Seconds);
            CSRedisHelper.SetBytes(key, Serialize(value), sec.Seconds);
        }

**Comment by 2881099** [comment]
现在没有 SetBytes 了，值参数接受 object 类型，可以是 值类型或byte[]或引用类型

**Comment by 2881099** [comment]
redis-server 服务器环境要 2.8+ 以上才支持 set key value expire

否则会报 ERR wrong number of arguments for 'set' command

v2.8以下
set key value 没问题
set key value expire 报上述错误

> > **CSRedis.RedisException: ERR wrong number of arguments for 'set' command**
> > **CSRedisHelper  就是基类的 RedisHelper ，为了防止跟系统原有的冲突**
> 
> 在 CSRedis.Internal.IO.RedisReader.ReadType()
> 在 CSRedis.Internal.Commands.RedisStatus.Nullable.Parse(RedisReader reader)
> 在 CSRedis.Internal.RedisConnector.Call[T](RedisCommand`1 command) 在 CSRedis.RedisClient.Write[T](RedisCommand`1 command)
> 在 CSRedis.RedisClient.Set(String key, Object value, Nullable`1 expirationSeconds, Nullable`1 condition)
> 在 CSRedis.CSRedisClient.<>c__DisplayClass15_0.b__0(RedisClient c, String k)
> 在 CSRedis.CSRedisClient.ExecuteScalar[T](String key, Func`3 hander) 在 CSRedis.CSRedisClient.SetBytes(String key, Byte[] value, Int32 expireSeconds, Nullable`1 exists)
> 在 CSRedisHelper.SetBytes(String key, Byte[] value, Int32 expireSeconds, Nullable`1 exists)
> 在 RedisHelper.Set(String key, Object value, DateTime expireTime) 位置
> 
> public static void Set(string key, object value, DateTime expireTime)
> {
> 
> ```
>         TimeSpan span = DateTime.Now.AddMinutes(30) - DateTime.Now;//默认为30分钟
>         if (expireTime > DateTime.Now)
>         {
>             span = expireTime - DateTime.Now;
>         }
>         TimeSpan sec = TimeSpan.Parse(span.Days + "." + span.Hours + ":" + span.Minutes + ":" + span.Seconds);
>         CSRedisHelper.SetBytes(key, Serialize(value), sec.Seconds);
>     }
> ```

**Comment by hellozhang** [comment]
Redis 运行一段时间后，会自动停止。

### 
> **报错 **”无法从传输链接中读取数据，远程主机强迫关闭了一个现有的链接“”****

**Comment by 2881099** [comment]
什么版本
