### ISSUE TITLE
ZRem 根据key和member移除无效

### ISSUE THREAD

**Issue by imgd** [2881099/csredis#453]
public class User
    {
        public long ID { get; set; }
        public string Name { get; set; }
    }

        [HttpPost]
        public async Task<long> Remove([FromBody]User user)
        {
           return await _redis.ZRemAsync(RedisKey, user);
        }

上面代码移除无效，下面代码就可以

如果我是根据查询出来的member去移除就可以
    var expireUsers = await redis.ZRevRangeByScoreAsync<User>(key, minScore, decimal.MinValue);
    if (expireUsers != null && expireUsers.Any())
    {
        var reustcus = await redis.ZRemAsync(key, expireUsers);
    }

经过测试ZRemAsync T 类型为string有效 其他类型无效
组件：CSRedisCore(3.8.3)

**Comment by 2881099** [comment]
是序列化问题，多一个空格都不行，尽量用 string 表示 key/field/member 吧

**Comment by imgd** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by imgd** [comment]
好吧，我看freeredis ZRem 也只封装了string的也是这个原因吗？

**Comment by 2881099** [comment]
是的
