### ISSUE TITLE
ExpireAt 设置过期时间多了8个小时

### ISSUE THREAD

**Issue by zhouxin93** [2881099/csredis#46]
我查了服务器用的是标准中国时间、Redis的时间也是同步的。但是我14:30设置当天17:30过期的key、生成出来的TTL却有11个小时。

**Comment by zhouxin93** [comment]
![tim 20181024144651](https://user-images.githubusercontent.com/20853017/47411760-5d00be80-d79c-11e8-9f13-95d78f44cfad.png)
![tim 20181024144838](https://user-images.githubusercontent.com/20853017/47411761-5d995500-d79c-11e8-9a80-9a6dc02829af.png)
![tim 20181024145150](https://user-images.githubusercontent.com/20853017/47411762-5e31eb80-d79c-11e8-9de8-e345580bbac4.png)

**Comment by 2881099** [comment]
请使用 rds.ExpireAt(DateTime.UtcNow)

**Comment by zhouxin93** [comment]
> 请使用 rds.ExpireAt(DateTime.UtcNow)

使用UtcNow也是一样。三万多秒过期。
目前我自己使用这种方式设置。只有不到9000秒。是正确的
`int timeStamp = (int)(data - DateTime.Now).TotalSeconds`

**Comment by 2881099** [comment]
刚才测试确实不方全，传入时间统一为本地

内部计算 unix_timestamp ToUniversalTime 再计算，这样比较合理

**Comment by zhouxin93** [comment]
> 刚才测试确实不方全，传入时间统一为本地
> 
> 内部计算 unix_timestamp ToUniversalTime 再计算，这样比较合理
