### ISSUE TITLE
如何实现模糊搜索

### ISSUE THREAD

**Issue by xiaohanlaila** [2881099/csredis#461]
大佬，请问如何实现模糊搜索功能

**Comment by 2881099** [comment]
RedisHelper.Scan("*" ,... 

后面的参数看下 [redis.cn ](http://redis.cn/commands/scan.html)

RedisHelper.Keys("*") 也可以，只不过会阻塞 redis-server，有风险。

如果使用 FreeRedis 就方便很多，[[开源福利] FreeRedis 历时两年正式发布 v1.0 [C#.NET Redis Client]](https://www.cnblogs.com/FreeSql/p/16667741.html)

```c#
foreach (var keys in cli.Scan("*", 10, null))
{
    Console.WriteLine(string.Join(", ", keys));
}
```

**Comment by xiaohanlaila** [comment]
好的，非常感谢
