### ISSUE TITLE
HSet操作返回值错误

### ISSUE THREAD

**Issue by njzyzd** [2881099/csredis#47]
redis Hset ：如果字段是哈希表中的一个新建字段，并且值设置成功，返回 1 。 如果哈希表中域字段已经存在且旧值已被新值覆盖，返回 0
更新的时候，程序里也和1比较了。

这里可能是为了性能，而忽略了

**Comment by 2881099** [comment]
感谢反馈，现在直接返回bool，貌似这个返回值没什么意义了，要么throw错误，要么肯定成功。

hsetnx 返回值比较有意义。

**Comment by daounet** [comment]
> 感谢反馈，现在直接返回bool，貌似这个返回值没什么意义了，要么throw错误，要么肯定成功。
> 
> hsetnx 返回值比较有意义。

另外今天测试，发现重连机制好像还是不行。
