### ISSUE TITLE
建议将Json依赖抽离

### ISSUE THREAD

**Issue by zhza** [2881099/csredis#470]
新版dotnet sdk已内置json格式化库，而本项目默认依赖第三方json库，在项目中使用时，同时维护两份json解析配置比较麻烦。
 建议高版本要么把格式化的功能延迟到使用侧，由使用者自定义指定解析方案。

**Comment by zhza** [comment]
报欠，找到自定义解析入口了。

**Comment by 2881099** [comment]
也可以考虑 FreeRedis，全面重构过
