### ISSUE TITLE
xread,xrevrange bug

### ISSUE THREAD

**Issue by snglw07** [2881099/csredis#472]
1. 这里没有处理 block=0的情况，block==0时会阻塞；       
public static RedisXReadCommand XRead(long count, long block, params (string key, string id)[] streams)
        {
            var args = new List<object>();
            if (count > 0) args.AddRange(new[] { "COUNT", count.ToString() });
            if (block > 0) args.AddRange(new[] { "BLOCK", block.ToString() });
            args.Add("STREAMS");
            args.AddRange(streams.Select(a => (object)a.key));
            args.AddRange(streams.Select(a => (object)a.id));
            return new RedisXReadCommand("XREAD", args.ToArray());
        }
2. 这里 end/start 的参数内部传反了,目前只有传 end="-",start="+" 才能正确执行，正确的应该是 end="+",start="-"
public (string id, string[] items)[] XRevRange(string key, string end, string start, long count = 1);

**Comment by 2881099** [comment]
建议切换到最新的 FreeRedis
