### ISSUE TITLE
同步方法与异步方法的重试机制存在差异

### ISSUE THREAD

**Issue by softworm** [2881099/csredis#473]
注意到 同步方法 `public T Call<T>(RedisCommand<T> command)` 中会尝试[重新打开连接](https://github.com/2881099/csredis/blob/fbad4f0b40f8fffbcd647efb6136e99bb134bb2c/src/CSRedisCore/Internal/RedisConnector.cs#L81)，

但异步方法`async public Task<T> CallAsync<T>(RedisCommand<T> command)` 并[没有此逻辑](https://github.com/2881099/csredis/blob/fbad4f0b40f8fffbcd647efb6136e99bb134bb2c/src/CSRedisCore/Internal/RedisConnector.cs#L132)。

这样导致当服务端主动关闭连接后在异步方法中不会产生重试效果，会直接抛出异常。

不知是否有意这样设计，或者存在某些难以处理的情况？

**Comment by 2881099** [comment]
欢迎切换到FreeRedis

**Comment by softworm** [comment]
老哥稳，因为使用了easycaching，不知是否有计划做freeredis与easycaching的适配？

**Comment by catcherwong** [comment]
@softworm  easycaching 已经在适配 freeredis 了，预计4月份会正式发布。

**Comment by softworm** [comment]
稳，感谢：）
