### ISSUE TITLE
执行ZRangeByScoreAsync方法后应用内存增加700MB

### ISSUE THREAD

**Issue by ZUOXIANGE** [2881099/csredis#477]
调用代码如下,实际得到的结果数据在1万左右
```csharp
await _redisClient.ZRangeByScoreAsync<CacheDto>(key, start, end);
```

连接字符串如下,是阿里云Redis主从版的

> redis.rds.aliyuncs.com:6379,password=123456,defaultDatabase=0,autoDispose=false,poolsize=200,idleTimeout=200000,testcluster=false,tryit=3

有什么排查方法和建议吗

**Comment by 2881099** [comment]
1万行数据所需的内存

**Comment by ZUOXIANGE** [comment]
但是数据用完之后内存占用还在,隔一天也不会GC,主动调用GC.Collect()也不行

**Comment by 2881099** [comment]
那要详细了解内存结构了，700mb 对于 netcoe 小意思，他不会释放到启动时的状态。

如果内存持续增长才是泄露。
