### ISSUE TITLE
可以让pub/sub直接发送或者接受byte[]参数吗？

### ISSUE THREAD

**Issue by yjqGitHub** [2881099/csredis#486]
您好，我在使用pub/sub过程中发现只能使用string来接收传递消息体，因为一些特殊原因我们需要使用byte[]来发送接收，后续可以支持吗？

**Comment by 2881099** [comment]
byte[]转成base64再发送

**Comment by yjqGitHub** [comment]
这样就多了一次序列化和反序列化了，希望能够减少这方面的转换

**Comment by 2881099** [comment]
我以为是 FreeRedis 的 issues，FreeRedis 支持了这种操作。

**Comment by 2881099** [comment]
建议切换到 FreeRedis，支持更高版本 redis 功能。

https://github.com/2881099/FreeRedis

> 支持 STRING、HASH、LIST、SET、ZSET、BITMAP、HyperLogLog、GEO、Stream 以及布隆过滤器等。

| 参数               | 默认值     | 说明 |
| :---------------- | --------: | :------------------- |
| protocol          | RESP2     | 若使用 RESP3 协议，你需要 Redis 6.0 环境 |
| user              | \<empty\> | Redis 服务端用户名，要求 Redis 6.0 环境 |
| password          | \<empty\> | Redis 服务端密码 |
| defaultDatabase   | 0         | Redis 服务端数据库 |
| max poolsize      | 100       | 连接池最大连接数 |
| min poolsize      | 5         | 连接池最小连接数 |
| idleTimeout       | 20000     | 连接池中元素的空闲时间（单位为毫秒 ms），适用于连接到远程服务器 |
| connectTimeout    | 10000     | 连接超时，单位为毫秒（ms） |
| receiveTimeout    | 10000     | 接收超时，单位为毫秒（ms） |
| sendTimeout       | 10000     | 发送超时，单位为毫秒（ms） |
| encoding          | utf-8     | 字符串字符集 |
| retry             | 0         | 协议发生错误时，重试执行的次数 |
| ssl               | false     | 启用加密传输 |
| name              | \<empty\> | 连接名，使用 CLIENT LIST 命令查看 |
| prefix            | \<empty\> | `key` 前辍，所有方法都会附带此前辍，cli.Set(prefix + "key", 111); |
| exitAutoDisposePool | true | AppDomain.CurrentDomain.ProcessExit/Console.CancelKeyPress 事件自动释放 |
| subscribleReadbytes | false | Subscrible 读取内容为 byte[] |

**Comment by yjqGitHub** [comment]
freeredis我看了代码它也是只支持发送string和接收string。我想要的是发送是byte[]，接收也是byte[]

**Comment by 2881099** [comment]
subscribleReadbytes=true

连接串加上这个就可以了

**Comment by yjqGitHub** [comment]
csredis 后续有计划支持这个吗

**Comment by 2881099** [comment]
可以新增一个组件，只是订阅发布用freeredis
