### ISSUE TITLE
感觉新版本没以前的好用了啊，很多命令需要自己单独设置超时时间了。

### ISSUE THREAD

**Issue by OAngs** [2881099/csredis#49]
为什么要这么设定呢？

**Comment by 2881099** [comment]
很多命令具体指哪些

**Comment by OAngs** [comment]
好象... 我在看看...
印象里以前操作列表的时候是可以同时设置默认时间的... 可能是我记错了？
挺多方法名都变了，可能是记错了...

**Comment by 2881099** [comment]
是的，GetBytes SetBytes 这种没有了。

**Comment by 2881099** [comment]
HashSet HashXxxx

全部改成与 redis-cli 命令一致，list 方法名没变化 。
