### ISSUE TITLE
cacheshell哈希表不支持设置-1永久有效

### ISSUE THREAD

**Issue by ZUOXIANGE** [2881099/csredis#500]
![image](https://github.com/2881099/csredis/assets/20124439/b8ec6d3d-fdea-4710-936a-7835d4422f35)

方便的话可以支持一下,我现在用的自己的扩展方法

**Comment by 2881099** [comment]
目前这个项目处于维护稳定状态，不修改机制

如果有新的想法，可以移步到 FreeRedis

**Comment by ZUOXIANGE** [comment]
FreeRedis没有cacheshell吧

**Comment by 2881099** [comment]
FreeRedis 没有 CacheShell 需要自己实现
