### ISSUE TITLE
请问可以监听redis键过期事件吗

### ISSUE THREAD

**Issue by yinsitan** [2881099/csredis#501]
![image](https://github.com/2881099/csredis/assets/86031918/81a3fb5d-8c49-4eab-8fa8-dc957b9110f1)

![image](https://github.com/2881099/csredis/assets/86031918/c96d6d5b-d299-4a3a-8718-4ce9c2307987)

好像没有效果欸

**Comment by 2881099** [comment]
服务器要开启一个配置，具体百度一下
