### ISSUE TITLE
SlowLogGetAsync

### ISSUE THREAD

**Issue by Wx19880221** [2881099/csredis#505]
csrediscore search slowlog。 redis version is 6, the slowlog message type contains 6 elements. when i use SlowLogGetAsync() method. The error specified 'export 4 elements but found 6'. How can I fixed it

**Comment by 2881099** [comment]
see https://github.com/2881099/FreeSql

**Comment by Wx19880221** [comment]
I use freeeRedis fix this issue. Any improve plan for csredis?

**Comment by 2881099** [comment]
FreeRedis is the next version of csredis, released in 2022.

**Comment by Wx19880221** [comment]
😳 Thanks!
