### ISSUE TITLE
关于 Publish 方法 {msgid}|

### ISSUE THREAD

**Issue by 2881099** [2881099/csredis#51]
/// <summary>
/// 用于将信息发送到指定分区节点的频道
/// </summary>
/// <param name="channel">频道名</param>
/// <param name="message">消息文本</param>
/// <returns></returns>
public long Publish(string channel, string message) {
var msgid = HIncrBy("csredisclient:Publish:msgid", channel, 1);
return ExecuteScalar(channel, (c, k) => c.Value.Publish(channel, $"{msgid}|{message}"));
}

大神，发布消息为什么加个{msgid}|

**Comment by 2881099** [comment]
这个参数是用于 Subscribe/PSubscribe 方法配合，防止订阅端收到重复消息。

**Comment by 2881099** [comment]
现更新一个标准的Publish方法，命名：PublishNoneMessageId

**Comment by scymen** [comment]
建议这个（及类似的） Issue 可以关了
