### ISSUE TITLE
大佬readme里面写的有瑕疵

### ISSUE THREAD

**Issue by PengTaoY** [2881099/csredis#53]
如果确定一定以及肯定非要有切换数据库的需求，请看以下代码：

......
下面的这段代码：
_for (var a = 0; a< redis.Length; a++) redis[a] = new CSRedisClient(connectionString + "; defualtDatabase=" + a);_
应该写成：
for (var a = 0; a< redis.Length; a++) redis[a] = new CSRedisClient(connectionString + ",defaultDatabase=" + a);

**Comment by 2881099** [comment]
谢谢提醒
