### ISSUE TITLE
集群使用方式

### ISSUE THREAD

**Issue by ArvinXiao** [2881099/csredis#55]
你好，我已经配置了redis集群，有几个问题请教下：
1. 请问下，集群的使用方式是什么？我使用的是如下的方式，但是readme中这种模式是分区模式：
new CSRedisClient(null, _cluster1, _cluster2, _cluster3)； (每一个cluster都是一个连接字符串)

2. readme中说，集群不支持pipline方式，但是我测试时，管道模式依然可以使用。

**Comment by 2881099** [comment]
??

**Comment by ArvinXiao** [comment]
>           ??
手抖了一下，还没写内容就发出去了。你的回答速度太快了，谢谢

**Comment by 2881099** [comment]
readme 中
1、集群模式，是指官方提供的；
2、分区模式，是我自己封装的；

两个有区别
集群模式遵从官方定义规范，管道模式跨节点会失败。
分区模式，最大化容忍跨节点操作。

集群模式更成熟可靠；
分区模式需要自己配置 rule 规则配置类似 slot 存储规则，和可用性检查规则；

集群模式使用，只需要指定其中任意一个节点的连接串即可，指定多个也可以；
> new CSRedisClient("集群某节点服务器的连接串")

分区模式使用，必须指定每个节点；
> new CSRedisClient(规则定义，node1, node2, node3)

**Comment by ArvinXiao** [comment]
集群模式使用，只需要指定其中任意一个节点的连接串即可，指定多个也可以；
=> 测试发现：
1. 如果只配置一个节点的连接字符串，当该节点down后，建立连接时没有抛出异常，但是执行写操作时会抛出异常：“Connection was not opened”, 使用的代码如下：

```
var client = new CSRedis.CSRedisClient(); //未抛出异常
RedisHelper.Initialization(client);
var result = RedisHelper.Set("TestKey", "Hello", 120); //抛出异常
```

2. 如何配置集群的多个连接字符串?是这种方式吗？：new CSRedisClient(null，node1, node2, node3)

**Comment by 2881099** [comment]
第一点，运行启动前down了，确实不行。
如果运行一段时间后，其他节点存在后再down，就不会出这个问题
第二点可以，节点多了管理麻烦很多。

第一点的优势，可以动态增加其他节点，免去配置环节。程序启动时候，配置的节点down了，可以换成了用的其他节点。

**Comment by 2881099** [comment]
比如程序运行中，对redis cluster增加节点，第一种方法不用改配置，切不用重启

**Comment by ArvinXiao** [comment]
我使用第一种方式配置连接字符串，运行一段时间后可以看到所有的master节点；但是我把连接字符串中配置的节点停止后(之后10分钟左右)，RedisHelper.Nodes中显示的仍然是所有的master节点，而且执行set操作时，还会抛出异常：“CLUSTERDOWN The cluster is down”

**Comment by 2881099** [comment]
https://blog.csdn.net/qq_35066345/article/details/79833609
可以参考这篇文章解决

**Comment by 2881099** [comment]
nodes只会增加，不会删除。slot自动更新和管理。

**Comment by ArvinXiao** [comment]
我不是想解决这个问题(“CLUSTERDOWN The cluster is down”)；节点是我故意停止，用来测试如果某一个几点down了(其他节点仍然在正常运行；我的理解是请求应该会到其他节点上)，客户端是否能正常运行

**Comment by 2881099** [comment]
了解，我举个例子。使用redis-cli -c

在node1执行
get a
moved slot node2

在node2执行
get a
(nil)

执行任何get，回到node1
执行
get a


此时返回什么

**Comment by 2881099** [comment]
对了，还是 moved node2，node2执行还是报错，因为down了。

集群有规范定义，客户端遵从转向规范。可以一起讨论怎么解决

**Comment by 2881099** [comment]
csredis配合做了转向，但是转向后的节点报错了

**Comment by xflag** [comment]
这个问题解决了吗？
就是集群环境下，假设3主3从
一开始new CSRedisClient("主A的IP")
连接后，一段时间，假设主A节点down了，副A升级为主结点，但csredisClient连接的还是主A的IP，这个IP已经连不上了，这样还能保持csredisClient正常工作吗？
看文档上写的，是这个效果吧。

**Comment by 2881099** [comment]
> 这个问题解决了吗？
> 就是集群环境下，假设3主3从
> 一开始new CSRedisClient("主A的IP")
> 连接后，一段时间，假设主A节点down了，副A升级为主结点，但csredisClient连接的还是主A的IP，这个IP已经连不上了，这样还能保持csredisClient正常工作吗？
> 看文档上写的，是这个效果吧。

可以，集群内部会管理好slot

**Comment by xflag** [comment]
> > 这个问题解决了吗？
> > 就是集群环境下，假设3主3从
> > 一开始new CSRedisClient("主A的IP")
> > 连接后，一段时间，假设主A节点down了，副A升级为主结点，但csredisClient连接的还是主A的IP，这个IP已经连不上了，这样还能保持csredisClient正常工作吗？
> > 看文档上写的，是这个效果吧。
> 
> 可以，集群内部会管理好slot

很好奇，csredisClient连接的主IP挂了后，之后的连接要怎么连接到redis集群的？能讲解一下原理吗？是不是csredisClient会缓存下之前请求时redis集群返回的MOVED和ASK的IP+端口，然后如果主IP连接不上后，就拿之前缓存的IP+端口来尝试连接。但这样还有一个极端情况，如果之前的请求都没有缓存到任何的MOVED和ASK，也就是说之前的请求都刚好请求到主IP的slot，那这时主IP挂了，会怎么样？

**Comment by 2881099** [comment]
> > > 这个问题解决了吗？
> > > 就是集群环境下，假设3主3从
> > > 一开始new CSRedisClient("主A的IP")
> > > 连接后，一段时间，假设主A节点down了，副A升级为主结点，但csredisClient连接的还是主A的IP，这个IP已经连不上了，这样还能保持csredisClient正常工作吗？
> > > 看文档上写的，是这个效果吧。
> > 
> > 
> > 可以，集群内部会管理好slot
> 
> 很好奇，csredisClient连接的主IP挂了后，之后的连接要怎么连接到redis集群的？能讲解一下原理吗？是不是csredisClient会缓存下之前请求时redis集群返回的MOVED和ASK的IP+端口，然后如果主IP连接不上后，就拿之前缓存的IP+端口来尝试连接。但这样还有一个极端情况，如果之前的请求都没有缓存到任何的MOVED和ASK，也就是说之前的请求都刚好请求到主IP的slot，那这时主IP挂了，会怎么样？

和你说的情况差不多，接收到moved时，正好网络问题，或者挂了会报错
