### ISSUE TITLE
获取超时怎么设置

### ISSUE THREAD

**Issue by shennwei** [2881099/csredis#56]
System.Exception: SafeObjectPool.Get 获取超时（10秒），设置 Policy.IsThrowGetTimeoutException 可以避免该异常。这个报错需要在哪设置呢

**Comment by 2881099** [comment]
链接池设置多大 poolsize，增大可以缓解这个错误。

**Comment by 2881099** [comment]
并发太大，链接池忙不过来才报的这个错误。

**Comment by 2881099** [comment]
并发大的项目，可以考虑使用异步方法，没有这个问题。
