### ISSUE TITLE
高并发下使用pipeline导致程序卡死

### ISSUE THREAD

**Issue by shennwei** [2881099/csredis#59]
代码中使用pipeline进行批量操作，压测时项目直接卡死，可能是什么问题啊

**Comment by 2881099** [comment]
请帖出测试代码及方法，谢谢

**Comment by shennwei** [comment]
![image](https://user-images.githubusercontent.com/10250518/48897549-58a3f000-ee85-11e8-9270-e582addd63b5.png)
这是服务端的接口
![image](https://user-images.githubusercontent.com/10250518/48897577-66597580-ee85-11e8-9efd-87363afd6b6e.png)
这是客户端的请求代码

服务端没有任何返回，另外在请求接口的话，服务拒绝请求
![image](https://user-images.githubusercontent.com/10250518/48897770-ec75bc00-ee85-11e8-9bfa-e74a7a2e0edd.png)

**Comment by 2881099** [comment]
可以用 apache ab 工具做压测。
.net core HttpClient 使用貌似不正确啊，很容易把套字节占满。

**Comment by 2881099** [comment]
Parallel.For(0, 1000, a => {
			var res = csredis.StartPipe().Get("abc" + a).Get("123" + a).EndPipe();
		});

使用上述代码测试，没有报出错误。

**Comment by shennwei** [comment]
这个只是一个测试代码，服务器上是使用的压测工具，确实是没有报错，但是程序会卡住

**Comment by 2881099** [comment]
卡死，有可能是Task队列太小，或者套字节用尽。

Parallel.For(0, 10000, a => {
	var res = csredis.StartPipe().Get("abc" + a).Get("123" + a).EndPipe();
});

1000 -> 10000 测试没有报错，也没有卡住。
你可以尝试把异步接口，改为同步试试。

**Comment by shennwei** [comment]
同步接口真的没问题

**Comment by shennwei** [comment]
改成同步接口进行压测后程序同样卡死，这次有报错信息了
   
![image](https://user-images.githubusercontent.com/10250518/48928368-22b04b80-ef19-11e8-8345-023f2aa03ef4.png)
![image](https://user-images.githubusercontent.com/10250518/48928371-26dc6900-ef19-11e8-8b73-03fbe744a01a.png)

**Comment by 2881099** [comment]
这个错误说明csredis正在释放了，怎么定义和使用的呢

**Comment by shennwei** [comment]
![image](https://user-images.githubusercontent.com/10250518/48928441-d4e81300-ef19-11e8-8c10-29442f45d5ff.png)
![image](https://user-images.githubusercontent.com/10250518/48928451-e2050200-ef19-11e8-99bc-7ce72abd6f28.png)


在startup中进行了配置，接口里直接使用的RedisHelper

**Comment by 2881099** [comment]
程序退出了吗？版本号是多少

**Comment by 2881099** [comment]
怎么测试的，另外最好升级到最新

**Comment by 2881099** [comment]
同步方法，并发不会太高，会阻塞

异步方法最好设大 TheadPool

**Comment by 2881099** [comment]
3.0.23 有这个bug
用 3.0.22 试

**Comment by shennwei** [comment]
可能是阿里云redis的问题，我再找找，非常感谢！
