### ISSUE TITLE
pipe publish 消息到频道，message_id 错误

### ISSUE THREAD

**Issue by scymen** [2881099/csredis#69]
正常情况：
string json = "xxxxxxxxx";
`RedisHelper.HMSet(rds_k, "online", DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss.fff"));
RedisHelper.Publish(RedisKey.DeviceStatusChannel, json);`

客户端订阅收到的信息与发布的信息是一致的，如：
` "32|{\"evt\":\"NewCnn\",\"ip_port\":\"127.0.0.1:10666\"}"`

使用pipline时
`RedisHelper.StartPipe()

.HMSet(rds_k, "online", DateTime.Now.ToString("yyyy-MM-ddTHH:mm:ss.fff"))

.Publish(RedisKey.DeviceStatusChannel, json)

.EndPipe();`

客户端口收到的订阅信息是：
`"CSRedis.CSRedisClientPipe`1[System.Int64]|{\"evt\":\"NewCnn\",\"ip_port\":\"127.0.0.1:11078\"}"`

似乎把 message_id 类型 toString 了？

**Comment by 2881099** [comment]
感谢反馈，问题已修复

**Comment by 2881099** [comment]
我的qq，2881099

**Comment by scymen** [comment]
谢谢
