### ISSUE TITLE
普通连接，但是pool.ClusterKey一直是127.0.0.1

### ISSUE THREAD

**Issue by jack2020** [2881099/csredis#7]
var csredis = new CSRedis.CSRedisClient("192.168.1.48:7001,defaultDatabase=15,poolsize=50");
var r1 = csredis.Set("aaa", DateTime.Now.ToString());
报异常CSRedis.RedisClientException:“Connection was not opened”

![image](https://user-images.githubusercontent.com/3782207/41905190-0450b110-796d-11e8-936b-512cb04e5e34.png)

**Comment by 2881099** [comment]
谢谢反馈
