### ISSUE TITLE
使用订阅时控制台输出显示信息为中文

### ISSUE THREAD

**Issue by scymen** [2881099/csredis#73]
这不是BUG，也不算是一个Issue。

Linux下，运行的程序控制台输出的信息如下：

正在订阅【127.0.0.1:6379/0】(channels:pro:log:chnl)/(chans:...............................

我在想如果服务器没有安装中文字体，或者没有预先设置SSH客户端，
这个中文能否正确显示，会不会乱码？
输出信息使用英文，是否应该更好一些？

**Comment by 2881099** [comment]
谢谢反馈，有时间我改成英文

**Comment by scymen** [comment]
谢谢
