### ISSUE TITLE
请问有无计划支持通配符查询数据集？

### ISSUE THREAD

**Issue by EdisonChou** [2881099/csredis#77]
在有些场景中需要得到某个通配符下的所有数据集，如 "Product:*" 会将 "Product:0xdfds90123123"、"Product:0xdfds90123124" 以及 "Product:0xdfds90123125" 都返回。但目前只有Scan和Keys支持返回某个pattern下的所有Keys，而没有Values，因此请问有这样的接口可以支持返回Values吗？否则，客户端需要首先拿到Keys，再遍历Get一遍组成一个List使用，在数据量大的时候需要循环遍历很多次，会影响一点性能。

**Comment by 2881099** [comment]
redis 提供的 sscan + keys 都只能返回 key，针对您说的若数据量较多时考虑性能问题的解决方法：

1、使用 scan 非阻塞方式，按批次量进行获取，每次获取500条；
2、使用 mget 或者其他批量获取的方法，对返回的 keys 进行取值；

**Comment by EdisonChou** [comment]
谢谢您的回答！

> redis 提供的 sscan + keys 都只能返回 key，针对您说的若数据量较多时考虑性能问题的解决方法：
> 
> 1、使用 scan 非阻塞方式，按批次量进行获取，每次获取500条；
> 2、使用 mget 或者其他批量获取的方法，对返回的 keys 进行取值；
