### ISSUE TITLE
注入时，依赖包不支持.netcore2.2?

### ISSUE THREAD

**Issue by daoqiang** [2881099/csredis#78]

**Comment by 2881099** [comment]
描述事情应该多附带些信息吧

包是 .netstandard 2.0 标准库，注不注入使用没有影响

**Comment by daoqiang** [comment]
好的不好意思，我重新描述一下，
文档中“分布式注入”，依赖一个Caching.CSRedis，也是std2.0的，但是这个包引入不了(nuget下载下来了)。黄色叹号。两个包版本都是3.0.31。我项目用的.netcore 2.2正式版

**Comment by 2881099** [comment]
使用控制台进入项目目录执行：
dotnet restore
dotnet build

把内容复制发上来

**Comment by daoqiang** [comment]
好了没问题了，有个依赖项目强行x86导致的。好的谢谢你

**Comment by 2881099** [comment]
不客气
