### ISSUE TITLE
密码问题带来的database索引被重置为0

### ISSUE THREAD

**Issue by jiangdaxia** [2881099/csredis#89]
版本：3.0.35.0
连接字符串：“127.0.0.1:6379,allowAdmin=true,defaultDatabase=13,poolsize=50,preheat=false,ssl=false,writeBuffer=10240,tryit=0,prefix=TH|”

1.服务端未启用密码
2.客户端指定密码
3.客户端指定defaultDatabase不为0

RedisClientPool 类 148 行 会进入catch 
错误为：Client sent AUTH, but no password is set
紧接着调用 obj.ResetValue() 方法重置。
实际结果是：数据被写入到了 index 为 0 的db里面
按照我的想法应该是：defaultDatabase还是得使用指定的.

后续代码没有继续跟，不知道这个将db index重置为0的操作是否为有意为之？

**Comment by 2881099** [comment]
实际结果是：数据被写入到了 index 为 0 的db里面
--------

未指定密码，后面的执行应该不会成功才对呀。

**Comment by 2881099** [comment]
哦哦，明白了。不是有意为之；

```csharp
_policy.Connected += (s, o) => {
	RedisClient rc = s as RedisClient;
	if (!string.IsNullOrEmpty(_policy._password)) rc.Auth(_policy._password);
	if (_policy._database > 0) rc.Select(_policy._database);
	onConnected(s as RedisClient);
};
```

因为 rc.Auth 报错，导致后面的 Select 没有执行。

**Comment by 2881099** [comment]
```csharp
_policy.Connected += (s, o) => {
	RedisClient rc = s as RedisClient;
	if (!string.IsNullOrEmpty(_policy._password)) {
		try {
			rc.Auth(_policy._password);
		} catch (Exception authEx) {
			if (authEx.Message != "Client sent AUTH, but no password is set")
				throw authEx;
		}
	}
	if (_policy._database > 0) rc.Select(_policy._database);
	onConnected(s as RedisClient);
};
```

我作一下兼容吧

**Comment by jiangdaxia** [comment]
好的，我这测试没问题了。
给作者赞一个，处理简直神速。
