### ISSUE TITLE
怎样切换数据库

### ISSUE THREAD

**Issue by hongbai** [2881099/csredis#9]
你好，按照实例在Startup中配置：
```
           var csredis= new CSRedis.CSRedisClient("172.16.8.222:6379,password=,defaultDatabase=11,poolsize=10,ssl=false,writeBuffer=10240");
            RedisHelper.Initialization(csredis,
              value => Newtonsoft.Json.JsonConvert.SerializeObject(value),
              deserialize: (data, type) => Newtonsoft.Json.JsonConvert.DeserializeObject(data, type));
            
            //注入Redis缓存
            services.AddSingleton<IDistributedCache>(new Microsoft.Extensions.Caching.Redis.CSRedisCache(RedisHelper.Instance));
```
之后，我要操作的数据，分别在同一个Redis服务器上的不同的db中，要在代码中切换数据库，请问应该如何操作？谢谢

**Comment by 2881099** [comment]
不建议一个 CSRedisClient 对象切换操作多个数据库，为什么呢？除非每次操作都做一次切换数据库操作，相当繁琐。

redis.Select(1);
redis.Set("key1", "1");

redis.Select(2);
redis.Get("key1");

正确姿势 ：

CSRedisClient rc1 = new CSRedisClient("127.0.0.1:6379,password=,defaultDatabase=1,poolsize=10,ssl=false,writeBuffer=20480,prefix=xx");

CSRedisClient rc2 = new CSRedisClient("127.0.0.1:6379,password=,defaultDatabase=2,poolsize=10,ssl=false,writeBuffer=20480,prefix=xx");
