### ISSUE TITLE
分区模式的使用

### ISSUE THREAD

**Issue by kingflyok** [2881099/csredis#95]
我今天使用了分区模式，遇到两个问题
1、构造函数中的参数是params string[]，导致我如果想通过配置文件配置加载的话，无法实现，因为第一个参数如果我写null，第二个参数加载string[]就会提示无法识别，和之前的哨兵模式构造函数冲突；
2、我自己模仿null的方法写了哈希之后，调用时候发现一个问题，系统当次运行时进行Set操作之后，用Get可以获取，停止运行之后直接运行Get操作始终无法查询到对应key
3、连续多次异步SetAsync报错

**Comment by 2881099** [comment]
## 问题1

问题确实存在，我考虑得不周全；临时方案：

![image](https://user-images.githubusercontent.com/16286519/53379856-377ffd80-39a6-11e9-81a3-4c02c470b174.png)

rds.Get("a") 定向了 3节点

----

![image](https://user-images.githubusercontent.com/16286519/53379895-58485300-39a6-11e9-8074-04b54c58dbe8.png)

rds.Get("b") 定向了 0节点

```csharp
CSRedisClient rds = null;
string[] rdsNodes = null;
var readConfigConnectionStrings = new[] {
	"127.0.0.1:6371,password=,defaultDatabase=1,poolsize=10,preheat=true,writeBuffer=10240,name=test,tryit=1",
	"127.0.0.1:6371,password=,defaultDatabase=2,poolsize=10,preheat=true,writeBuffer=10240,name=test,tryit=1",
	"127.0.0.1:6371,password=,defaultDatabase=3,poolsize=10,preheat=true,writeBuffer=10240,name=test,tryit=1",
	"127.0.0.1:6371,password=,defaultDatabase=4,poolsize=10,preheat=true,writeBuffer=10240,name=test,tryit=1"
}; //new string[10];
//从配置文件中读取数组
rds = new CSRedisClient(key => {
	var idx = CSRedisClient.GetClusterSlot(key ?? string.Empty) % rdsNodes.Length;
	return idx < 0 || idx >= rdsNodes.Length ? rdsNodes[0] : rdsNodes[idx];
}, readConfigConnectionStrings);
rdsNodes = rds.Nodes.Keys.ToArray();
```

## 问题2

GetHashCode 每次运行的结果确实不一样，可以考虑使用 CRC16 算法，即上面的 CSRedisClient.GetClusterSlot

## 问题3

如何重现？

**Comment by 2881099** [comment]
## 问题3、连续多次异步SetAsync报错

```csharp
Task.Run(async () => {
	await rds.SetAsync("a", 111);
	await rds.SetAsync("b", 111);
	await rds.SetAsync("c", 111);
	await rds.SetAsync("d", 111);
}).Wait();
```

运行正常

**Comment by kingflyok** [comment]
谢谢大佬的及时回复，第三个问题，我是直接用的
await rds.SetAsync("a", 111);
await rds.SetAsync("b", 111);
await rds.SetAsync("c", 111);
await rds.SetAsync("d", 111);
没用 Task.Run(async () => {
}).Wait()

**Comment by 2881099** [comment]
不客气。

await rds.SetAsync 在 Task + async 方法里才能执行。

Task.Run(async () => {
}).Wait() 是模拟运行的环境。

所以你到底是怎么写的呢？


rds.SetAsync("a", 111);
rds.SetAsync("b", 111);
rds.SetAsync("c", 111);
rds.SetAsync("d", 111);
这样？

**Comment by kingflyok** [comment]
大佬，
通过这样的方式存入Token
await Cache.SetAsync(token.ToRedisKey(RedisPrefix.Token), user.UserSecret, 120 * 60);
这样的方式获取Token
securityKey = mCache.Get(securityToken.ToRedisKey(RedisPrefix.Token));

我的微服务运行的时候，写入=>读取是OK的，但是我重启微服务之后就无法读取了，读取到的时钟是NULL

`// 获取全部集群节点配置
            string[] nodes = configuration.GetSection("RedisUrls").GetChildren().ToArray().Select(x => x.Value).ToArray();
            // 实例化CS客户端
            CSRedisClient csredis = new CSRedisClient(key =>
            {
                //var idx = Math.Abs(string.Concat(x).GetHashCode()) % nodes.Count();
                //return idx < 0 || idx >= nodes.Count() ? nodes[0] : nodes[idx];
                var idx = CSRedisClient.GetClusterSlot(key ?? string.Empty) % nodes.Length;
                return idx < 0 || idx >= nodes.Length ? nodes[0] : nodes[idx];
            }, nodes);
       
            // 初始化
            RedisHelper.Initialization(csredis);
            // 注册mvc分布式缓存
            services.AddSingleton<CSRedisClient>(RedisHelper.Instance);`

**Comment by 2881099** [comment]
你的代码中 nodes 是多个分区的连接字符串，和我上面发的代码不一样：
```csharp
CSRedisClient rds = null;
string[] rdsNodes = null; //请看这行
var readConfigConnectionStrings = new[] {
	"127.0.0.1:6371,password=,defaultDatabase=1,poolsize=10,preheat=true,writeBuffer=10240,name=test,tryit=1",
	"127.0.0.1:6371,password=,defaultDatabase=2,poolsize=10,preheat=true,writeBuffer=10240,name=test,tryit=1",
	"127.0.0.1:6371,password=,defaultDatabase=3,poolsize=10,preheat=true,writeBuffer=10240,name=test,tryit=1",
	"127.0.0.1:6371,password=,defaultDatabase=4,poolsize=10,preheat=true,writeBuffer=10240,name=test,tryit=1"
}; //new string[10];
//从配置文件中读取数组
rds = new CSRedisClient(key => {
	//再看看这里
	var idx = CSRedisClient.GetClusterSlot(key ?? string.Empty) % rdsNodes.Length;
	return idx < 0 || idx >= rdsNodes.Length ? rdsNodes[0] : rdsNodes[idx];
}, readConfigConnectionStrings);
rdsNodes = rds.Nodes.Keys.ToArray(); //也看看这里
```

**Comment by kingflyok** [comment]
原来里面的rdsNodes不是多个分区连接字符串啊 晕 明天我试一下

**Comment by kingflyok** [comment]
谢谢大佬 已经搞定咯
